### ISSUE TITLE
templates don't install 

### ISSUE THREAD

**Issue by bhcopeland** [elastic/ansible-elasticsearch#166]
I am trying to install fresh elasticsearch setup, but the templates fail to install:

```
RUNNING HANDLER [ansible-elasticsearch : Install templates without auth] *******
File lookup using /etc/elasticsearch/templates/default.json as file
fatal: [elk.xx.org]: FAILED! => {"failed": true, "msg": "the file_name '/etc/elasticsearch/templates/default.json' does not exist, or is not readable"}
File lookup using /etc/elasticsearch/templates/default.json as file
fatal: [elk.xx.org]: FAILED! => {"failed": true, "msg": "the file_name '/etc/elasticsearch/templates/default.json' does not exist, or is not readable"}
```

```
/etc/elasticsearch/templates # ls -la
total 16
drwxr-xr-x 2 elasticsearch elasticsearch 4096 Oct 10 14:38 .
drwxr-x--- 7 root          elasticsearch 4096 Sep 29 00:00 ..
-rw-r--r-- 1 elasticsearch elasticsearch  134 Sep 29 19:43 default.json
-rw-r--r-- 1 elasticsearch elasticsearch 1376 Oct 10 14:38 logstash.json
```

**Comment by pixelrebel** [comment]
The problem lies in permissions. This will almost certainly fail if the ansible control user is any user other than `root` or `"{{ es_user }}"` For this particular task, it is easily solved with:

```
become: yes
become_user: "{{ es_user }}"
```

But, then you quickly learn in the following task that the permissions problem goes deeper:

```
- name: Install templates without auth
  uri:
    url: "http://{{ es_api_host }}:{% if es_config['http.port'] is defined %}{{es_config['http.port']}}{% else %}{{es_api_port}}{% endif %}/_template/{{item.path | filename}}"
    method: PUT
    status_code: 200
    body_format: json
    body: "{{ lookup('file', item.path) }}"
  when: not es_enable_xpack or not es_xpack_features is defined or not '"shield" in es_xpack_features'
  with_items: "{{ templates.files }}"
```

Fails with `...could not locate file in lookup: /etc/elasticsearch/templates/syslog.json...`

According to [ansible lookups docs](http://docs.ansible.com/ansible/playbooks_lookups.html):
>Caution: Since this runs on the ansible host as the user running the playbook, and “become” does not apply, the target file must be readable by the playbook user, or, if it does not exist, the playbook user must have sufficient privileges to create it. 

So the above error can't be solved with `become`.  It is my opinion that `es_templates` should have been a list of json filenames instead of a boolean.  This would also allow for a user to select which templates to deploy from a larger library in `files/templates/`. I'd like to submit a PR for this, but I would appreciate guidance on the name of the default variable.  We can't simply make `es_templates` a list because it will break backwards compatibility.  How about `es_template_files`?  This would also make `es_templates` obsolete.

Example usage:

```
es_template_files:
  - syslog.json
  - logstash.json
  - vmware.json
```
