### ISSUE TITLE
How to configure a snapshots repository?

### ISSUE THREAD

**Issue by jlecour** [elastic/ansible-elasticsearch#171]
Hi,

I'd like to configure my Elasticsearch nodes with a snapshots repository for backups.

If I add the correct setting in the config hash, Elasticsearch refuses to start since the directory doesn't exist.
If I create it before executing the role, I get an error since the `elasticsearch` user/group doesn't exists yet.

What would be the proper way to do this ?

I can see it working with a task to create the directory but with broad Unix rights (allowing Elasticsearch to pass the bootstrap checks), then changing the ownership when the user/group exists.

Another way would be to start the cluster without the repository configured then amending the configuration to add it.

I don't really like both those options :/

**Comment by barryib** [comment]
@jlecour A good question which I don't have a "good" answer.

But is the following solution ok for you?

1. Create ES user and group first. You could (if you want) fix the user id and the group id
2. Create the required directory with correct user rights set
3. Run the ansible-elasticsearch role by setting these variables
```yml
es_user_id: xxxx
es_group_id: yyyy

# If you want to change default user and group
es_user: elasticsearch
es_group: elasticsearch
```
