### ISSUE TITLE
rule complains about es_api_basic_auth_username and es_api_basic_auth_password not being set, although shield is not getting installed

### ISSUE THREAD

**Issue by Thermi** [elastic/ansible-elasticsearch#190]
The rule in the latest version with commit a4a0329df7aa8c5848c1cc2dc1f1940c254953f0 complains about es_api_basic_auth_username and es_api_basic_auth_password not being set, although shield is not getting installed.

```
- hosts: master_nodes
  roles:
    - role: centos7-setup
    - role: elasticsearch
      sudo: true
      es_instance_name: "{{ ansible_hostname }}"
      es_heap_size: "1g"
      es_plugins_reinstall: true
      es_config:
        node.name: "{{ ansible_hostname }}"
        discovery.zen.ping.multicast.enabled: false
        discovery.zen.minimum_master_nodes: 2
        network.publish_host: "{{ ansible_eth0.ipv4.address }}"
        network.host: "{{ ansible_eth0.ipv4.address }}"
        discovery.type: "ec2"
        network.bind_host: "{{ ansible_eth0.ipv4.address }}"
        http.port: 9200
        transport.tcp.port: 9300
        node.data: false
        node.master: true
        bootstrap.mlockall: false
        cluster.name: "monitoring-cluster"
        cloud.aws.region: "eu-west-1"
        discovery.ec2.groups:
          - sg-645eb702
          - sg-185eb77e
          - sg-185eb77e
        discovery.ec2.availability_zones: "eu-west-1a"
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_plugins:
     - plugin: cloud-aws
    es_xpack_features:
      - marvel-agent
    es_enable_xpack: true

```

Output:

```
[...]
TASK [elasticsearch : os-specific vars] ****************************************                                                                                                      [25/627]
ok: [54.229.23.13]
ok: [54.171.60.75]
ok: [54.229.218.88]

TASK [elasticsearch : fail] ****************************************************
skipping: [54.229.23.13]
skipping: [54.229.218.88]
skipping: [54.171.60.75]

TASK [elasticsearch : fail] ****************************************************
skipping: [54.229.23.13]
skipping: [54.229.218.88]
skipping: [54.171.60.75]

TASK [elasticsearch : set_fact] ************************************************
ok: [54.229.23.13]
ok: [54.229.218.88]
ok: [54.171.60.75]

TASK [elasticsearch : debug] ***************************************************
skipping: [54.229.23.13]
skipping: [54.229.218.88]
skipping: [54.171.60.75]

TASK [elasticsearch : debug] ***************************************************
skipping: [54.229.23.13]
skipping: [54.229.218.88]
skipping: [54.171.60.75]

TASK [elasticsearch : debug] ***************************************************
ok: [54.229.23.13] => {
    "msg": "WARNING - It is recommended you specify the parameter 'discovery.zen.ping.unicast.hosts' when multicast is disabled"
}
ok: [54.229.218.88] => {
    "msg": "WARNING - It is recommended you specify the parameter 'discovery.zen.ping.unicast.hosts' when multicast is disabled"
}
ok: [54.171.60.75] => {
    "msg": "WARNING - It is recommended you specify the parameter 'discovery.zen.ping.unicast.hosts' when multicast is disabled"
}


TASK [elasticsearch : fail] ****************************************************
skipping: [54.229.23.13]
skipping: [54.229.218.88]
skipping: [54.171.60.75]

TASK [elasticsearch : fail] ****************************************************
skipping: [54.229.23.13]
skipping: [54.171.60.75]
skipping: [54.229.218.88]

TASK [elasticsearch : fail] ****************************************************
fatal: [54.229.23.13]: FAILED! => {"changed": false, "failed": true, "msg": "Enabling shield requires an es_api_basic_auth_username and es_api_basic_auth_password to be provided to allow clu
ster operations"}
fatal: [54.229.218.88]: FAILED! => {"changed": false, "failed": true, "msg": "Enabling shield requires an es_api_basic_auth_username and es_api_basic_auth_password to be provided to allow cl
uster operations"}
fatal: [54.171.60.75]: FAILED! => {"changed": false, "failed": true, "msg": "Enabling shield requires an es_api_basic_auth_username and es_api_basic_auth_password to be provided to allow clu
ster operations"}
        to retry, use: --limit @/home/thermi/UNITS/Rimoto/ansible/es-cluster.retry

PLAY RECAP *********************************************************************
54.171.60.75               : ok=21   changed=1    unreachable=0    failed=1   
54.229.218.88              : ok=21   changed=1    unreachable=0    failed=1   
54.229.23.13               : ok=21   changed=1    unreachable=0    failed=1
