### ISSUE TITLE
xpack and marvel

### ISSUE THREAD

**Issue by Thermi** [elastic/ansible-elasticsearch#202]
Hello,

I'm running an ES 2.4.2 cluster on AWS. Installed using ansible-elasticsearch.
As far as I am aware, marvel and logstash should be part of xpack. However, when installing xpack and setting marve-agent as feature of xpack, there are no performance or monitoring data fed into the kibana marvel application.
I can also not find any files or directories in the FS of the cluster nodes that contain "marvel" in the name.
That indicates that marvel-agent is not being installed. Is that a bug or am I just being stupid?

**Comment by Thermi** [comment]
Hm. Additionally to there not being any plugins installed when defined as part of xpack, when one tries to install them using es_plugins, installation fails when it's already installed. So the playbook currently does not reinstall plugins, although `es_plugins_reinstall: true` is set.
That's part of the playbook:
```
- hosts: master_nodes
  roles:
    - role: centos7-setup
    - role: elasticsearch
      sudo: true
      es_instance_name: "{{ ansible_hostname }}"
      es_heap_size: "1g"
      es_plugins_reinstall: true
      es_config:
        node.name: "{{ ansible_hostname }}"
        discovery.zen.ping.multicast.enabled: false
        discovery.zen.minimum_master_nodes: 2
        network.publish_host: "{{ ansible_eth0.ipv4.address }}"
        network.host: "{{ ansible_eth0.ipv4.address }}"
        discovery.type: "ec2"
        network.bind_host: "{{ ansible_eth0.ipv4.address }}"
        http.port: 9200
        transport.tcp.port: 9300
        node.data: false
        node.master: true
        bootstrap.mlockall: false
        cluster.name: "monitoring-cluster"
        cloud.aws.region: "eu-west-1"
        discovery.ec2.groups:
          - sg-645eb702
          - sg-185eb77e
          - sg-185eb77e
        discovery.ec2.availability_zones: "eu-west-1a"
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_plugins:
     - plugin: cloud-aws
     - plugin: license
     - plugin: marvel-agent
    es_xpack_features:
      - marvel-agent

```

**Comment by Thermi** [comment]
I'd like to get some feedback from elastic here.

**Comment by jakommo** [comment]
Hi @Thermi I was able to reproduce the plugin install not working, unfortunately I don't have a solution yet and it will take some days until I have time to look into this in more detail. 

About your initial problem, is the plugin installed? By default it should index the marvel data into it's own cluster. 
If you don't see any marvel indices, it might be worth checking the logs for any messages related to marvel.

**Comment by Thermi** [comment]
Nope, Marvel-Agent does not seem to be installed. At least I can't seem to find it in the FS.There are no messages in the logs of elasticsearch, nor is there any index that seems to have anything to do with marvel.

**Comment by jakommo** [comment]
@Thermi can you try:

```
    es_plugins:
     - plugin: cloud-aws
     # - plugin: license
     #- plugin: marvel-agent
    es_enable_xpack: true
    es_xpack_features:
      - marvel-agent
```
so that `license` (installed automatically) and `marvel-agent` are exclusively handled by `es_xpack_features`.
