### ISSUE TITLE
Call to pip fails if python2-pip package isn't installed on CentOS7

### ISSUE THREAD

**Issue by dokuhebi** [elastic/ansible-elasticsearch#215]
In elasticsearch-RedHat.yml, the call to "pip: name=httplib2" fails on CentOS7 if the python2-pip package isn't installed.  Probably should ensure the package exists before using pip.

Adding the following line just prior fixed it for me to install from epel.

```
# Ensure pip is installed 
- name: RedHat - Install python2-pip
  yum:
    name: python2-pip
    state: latest
```

However, if you have the epel repositories, you should just be able to use the following instead of using pip:

```
# ansible uri module requires python-httplib2
- name: RedHat - Install python-httplib2
  yum:
    name: python-httplib2
    state: latest
```
