### ISSUE TITLE
Some sort of timing issue with templates in handlers

### ISSUE THREAD

**Issue by welchwilmerck** [elastic/ansible-elasticsearch#238]
The timestamp on basic.json on the problem instance is several minutes prior to the handler activating. Have to run playbook several times (once for each ec2 instance, maybe) before handler sees basic.json for every instance.

```
RUNNING HANDLER [elasticsearch : Install templates without auth] ***************
 [WARNING]: Unable to find '/etc/elasticsearch/templates/basic.json' in expected paths.

File lookup using None as file
fatal: [54_40_186_183]: FAILED! => {
    "failed": true,
    "msg": "could not locate file in lookup: /etc/elasticsearch/templates/basic.json"
}

RUNNING HANDLER [elasticsearch : Install templates with auth] ******************
	to retry, use: --limit @/Users/welchwil/gendb_cluster_devops/ansible/cluster.retry

PLAY RECAP *********************************************************************
54_40_186_108              : ok=17   changed=12   unreachable=0    failed=0
54_40_186_183              : ok=64   changed=34   unreachable=0    failed=1
54_40_186_199              : ok=17   changed=12   unreachable=0    failed=0
54_40_186_246              : ok=17   changed=12   unreachable=0    failed=0
localhost                  : ok=10   changed=5    unreachable=0    failed=0

```
```
$ ansible tag_Name_billtest_es5new -b -m command -a 'ls -l /etc/elasticsearch/templates'
54_40_186_183 | SUCCESS | rc=0 >>
total 4
-rw-r--r-- 1 elasticsearch elasticsearch 157 Jan 18 22:32 basic.json

54_40_186_108 | FAILED | rc=2 >>
ls: cannot access /etc/elasticsearch/templates: No such file or directory

54_40_186_199 | FAILED | rc=2 >>
ls: cannot access /etc/elasticsearch/templates: No such file or directory

54_40_186_246 | FAILED | rc=2 >>
ls: cannot access /etc/elasticsearch/templates: No such file or directory
```

**Comment by gingerwizard** [comment]
@welchwilmerck im curious are you running multiple concurrent threads when running this playbook? My concern is the handler is fired for the first host and this is interfering with the other hosts which don't have the file yet.

**Comment by gingerwizard** [comment]
Can you also attach your playbook?

**Comment by gingerwizard** [comment]
Maybe related https://github.com/elastic/ansible-elasticsearch/issues/166

**Comment by gingerwizard** [comment]
@welchwilmerck im going to rework the template code as i believe this is reproducible.

**Comment by welchwilmerck** [comment]
I've changed my playbook considerably and updated to the latest commit of this role since I saw this issue and I can't reproduce ATM. Getting stopped at some other error (below). I'll work through the other errors, but didn't want your attention to this issue to go unacknowledged. For reference, no multiple threads. I'm running just one playbook with the default strategy.

task path: /Users/welchwil/gendb_cluster_devops/ansible/roles/elasticsearch/tasks/elasticsearch-config.yml:5
failed: [54_40_186_111] (item=/etc/elasticsearch/master) => {"failed": true, "gid": 0, "group": "root", "item": "/etc/elasticsearch/master", "mode": "0755", "msg": "chown failed: failed to look up user elasticsearch", "owner": "root", "path": "/etc/elasticsearch", "size": 4096, "state": "directory", "uid": 0}

**Comment by gingerwizard** [comment]
We're going to re-do the template handing - i see potential issues with it and am suprised its worked for anyone.

Are you installing ES via the tar or rpm/deb? The former create the elasticsearch user. If not, you'll need to either:

1. Create these by specifying the parameter es_user_id and es_group_id params as well as optionally setting es_user and es_group - the defaults for the latter 2 are elasticsearch.
OR
2. Otherwise create the user/group outside of the role and simply set es_user and es_group.

**Comment by welchwilmerck** [comment]
Currently, install from deb, option 2. Got that part figured out.

Now, seeing a different problem in roles/elasticsearch/tasks/elasticsearch-templates.yml. Will continue to troubleshoot.

First run, fails on first host and playbook halts immediately. No PLAY RECAP.
```
TASK [elasticsearch : Ensure security conf directory exists] ********
ok: [54_40_186_16]
ok: [54_40_186_160]

TASK [elasticsearch : Set Plugin Directory Permissions] *************
changed: [54_40_186_16]
changed: [54_40_186_160]

TASK [elasticsearch : file] *****************************************
changed: [54_40_186_16]
changed: [54_40_186_160]

TASK [elasticsearch : Copy default templates to elasticsearch] ******
ERROR! The requested handler 'load-templates' was not found in either the main handlers list nor in the listening handlers list
$
```
next run:
works for both hosts
```
TASK [elasticsearch : Copy default templates to elasticsearch] ******
ok: [54_40_186_160]
ok: [54_40_186_16]

TASK [elasticsearch : Copy templates to elasticsearch] **************

RUNNING HANDLER [elasticsearch : restart elasticsearch] *************
changed: [54_40_186_160]
changed: [54_40_186_16]

TASK [elasticsearch : Wait for elasticsearch to startup] ************
ok: [54_40_186_160]
ok: [54_40_186_16]
```

**Comment by welchwilmerck** [comment]
I found the problem - an ongoing issue in ansible regarding using include: to have multiple tasks in one handler - https://github.com/ansible/ansible/issues/15915

This silently fails to parse in the version of ansible I'm using (ansible 2.3.0):
```
- name: load-templates
  include: ./handlers/elasticsearch-templates.yml
  when: es_templates
```

Renamed issue accordingly.

**Comment by welchwilmerck** [comment]
Here's the ansible issue with handler blocks - https://github.com/ansible/ansible/issues/20603.

To work around, move load-templates to the top of handlers/main.yml

and now can reproduce the original issue: 

```
RUNNING HANDLER [elasticsearch : Install templates with auth] ****************************************************************
 [WARNING]: Unable to find '/etc/elasticsearch/templates/basic.json' in expected paths.

File lookup using None as file
fatal: [54_40_186_143]: FAILED! => {
    "failed": true,
    "msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: /etc/elasticsearch/templates/basic.json"
}
```

To repeat, just go to the target machine and rm /etc/elasticsearch/templates/basic.json

**Comment by welchwilmerck** [comment]
I see the bug, now. In the handler, you're using lookup to pull in the contents of a file as the body of a PUT to ES. Unfortunately, lookups run on the local machine, not the remote machine. As I don't have ES installed locally, I get outright 'file not found'. Somebody with a local install with matching template names will PUT their local files, not the ones declared in Ansible.

Further, this is a cluster operation, not a per host operation, so the handler should run once for the entire playbook. I can see adapting the idea in [http://stackoverflow.com/questions/41556574/run-an-ansible-handler-only-once-for-the-entire-playbook](url). As the final play only needs to run on localhost, collect the set of changed templates instead of changed hosts.

**Comment by welchwilmerck** [comment]
Here's my implementation of 'one-time play for cluster operations':

1. Must set `es_templates_fileglob`. Simplest way to make templates visible to tasks in both `role/elasticsearch` and the cluster ops play in the same playbook run. I set it to a directory outside `role/elasticsearch` to reflect a realistic use case.

```sh
ansible-playbook ... -e es_templates_fileglob="{{playbook_dir + '/files/templates/*.json'}}"
```

2. (optional) Rewrite `tasks/elasticsearch-templates.yml` to be clear that it's an if-then-else:

```yaml
- file: path=/etc/elasticsearch/templates state=directory owner={{ es_user }} group={{ es_group }}

- name: Copy example templates to cluster machines unless overridden
  copy: src=templates dest=/etc/elasticsearch/ owner={{ es_user }} group={{ es_group }}
  notify: load-templates
  when: es_templates_fileglob is not defined

- name: Copy locally defined templates instead of examples
  copy: src={{ item }} dest=/etc/elasticsearch/templates owner={{ es_user }} group={{ es_group }}
  notify: load-templates
  with_fileglob: "{{ es_templates_fileglob }}"
  when: es_templates_fileglob is defined
```

3. Change `handlers/elasticsearch-templates.yml` to just set a flag:

```yaml
- name: Ensure elasticsearch is started
  service: name={{instance_init_script | basename}} state=started enabled=yes

- name: Wait for elasticsearch to startup
  wait_for: host={{es_api_host}} port={{es_api_port}} delay=10

- name: Flag that something changed in templates
  add_host:
    hostname: localhost
    es_changed_templates: true
```

4. Add one-time play for cluster operations:

```yaml
---
  - name: Set flag for some template changed just as in handlers/elasticsearch-templates.yml
    hosts: "{{ es_cluster_name }}"
    tasks:
      - add_host:
          hostname: localhost
          es_changed_templates: true

  - name: end of management of ES nodes -- run cluster operations one-time
    hosts: "{{ es_cluster_name }}"
    connection: local
    gather_facts: false

    vars:
      es_api_host: "0.0.0.0"
      es_api_port: 9200
      es_enable_xpack: true
      es_xpack_features:
        - security

    tasks:

      # ln -s roles/elasticsearch/filter_plugins/ to make filename visible
      - name: Install templates without auth
        uri:
          url: "http://{{es_api_host}}:{{es_api_port}}/_template/{{(item | filename)}}"
          method: PUT
          status_code: 200
          body_format: json
          body: "{{ lookup('file', item) }}"
        when: (not es_enable_xpack or not es_xpack_features is defined or "security" not in es_xpack_features)
               and hostvars['localhost']['es_changed_templates'] is defined and hostvars['localhost']['es_changed_templates']
        with_fileglob: "{{ es_templates_fileglob }}"
        delegate_to: localhost

      - name: Install templates with auth
        uri:
          url: "http://{{es_api_host}}:{{es_api_port}}/_template/{{ item | filename }}"
          method: PUT
          status_code: 200
          user: "{{es_api_basic_auth_username}}"
          password: "{{es_api_basic_auth_password}}"
          force_basic_auth: yes
          body_format: json
          body: "{{ lookup('file', item) }}"
        when: es_enable_xpack and es_xpack_features is defined and "security" in es_xpack_features
              and hostvars['localhost']['es_changed_templates'] is defined and hostvars['localhost']['es_changed_templates']
        with_fileglob: "{{ es_templates_fileglob }}"
        delegate_to: localhost

    run_once: true
...
```
