### ISSUE TITLE
[2.x] "RepresenterError: cannot represent an object: 10.2.1.132"

### ISSUE THREAD

**Issue by Thermi** [elastic/ansible-elasticsearch#246]
When running the playbook from the 2.x branch to reconfigure a part of an existing cluster, the following error message is printed and the playbook run stops:

```
TASK [elasticsearch : Copy Configuration File] *********************************
fatal: [54.154.98.206]: FAILED! => {"changed": false, "failed": true, "msg": "RepresenterError: cannot represent an object: 10.2.1.132"}
fatal: [54.171.221.104]: FAILED! => {"changed": false, "failed": true, "msg": "RepresenterError: cannot represent an object: 10.2.1.133"}
        to retry, use: --limit @/home/thermi/UNITS/Rimoto/ansible/new-es-cluster.retry
```

```
- hosts: data_nodes
  roles:
    - role: centos7-setup
    - role: es-data
      es_data_dirs: "/opt/elasticsearch"
    - role: elasticsearch
      sudo: true
      es_plugins_reinstall: true
      es_instance_name: "{{ ansible_hostname }}"
      es_data_dirs: "/opt/elasticsearch"
      es_config:
        node.name: "{{ ansible_hostname }}"
        discovery.zen.ping.multicast.enabled: false
        discovery.zen.minimum_master_nodes: 1
        network.publish_host: "{{ ansible_eth0.ipv4.address }}"
        network.host: "{{ ansible_eth0.ipv4.address }}"
        discovery.type: "ec2"
        network.bind_host: "{{ ansible_eth0.ipv4.address }}"
        http.port: 9200
        transport.tcp.port: 9300
        node.data: true
        node.master: true
        bootstrap.mlockall: false
        cluster.name: "monitoring-cluster"
        cloud.aws.region: "eu-west-1"
        discovery.ec2.groups:
          - sg-645eb702
          - sg-185eb77e
          - sg-185eb77e
        discovery.ec2.availability_zones: "eu-west-1a"
        discovery.zen.ping.unicast.hosts:
          - "ip-10-2-1-132.eu-west-1.compute.internal:9300"
          - "ip-10-2-1-133.eu-west-1.compute.internal:9300"
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: true
    es_enable_xpack: true
    es_plugins:
     - plugin: cloud-aws
    es_xpack_features:
#      - license
      - marvel-agent
```
