### ISSUE TITLE
"msg": "RepresenterError: cannot represent an object: bootstrap.mlockall" }

### ISSUE THREAD

**Issue by chaica** [elastic/ansible-elasticsearch#257]
Hi,

Executing the ansible-elasticsearch ansible role, I get the following error:
```
"msg": "RepresenterError: cannot represent an object: bootstrap.mlockall" }
```

Here is my configuration yml file:
```
---
# Discover automaticaly the cluster with the instance name
es_cluster_discovery: yes

# Node configuration
es_heap_size: 8g
es_node_domain: bin.company.group

# Licnse activation
es_activate_license: true

# Shield configuration
es_use_shield: true
es_ldap_url: ldap://exead01.company.group
es_ldap_domain: company.group

# ES settings
es_settings:
  discovery.zen.ping.multicast.enabled: false
  http.port: 9200
  transport.tcp.port: 9300
  network.host:
    - _eth1_
    - _eth0_
    - _local_
  network.publish_host: _eth1_
  node.data: true
  node.master: true
  bootstrap.mlockall: true
  index.number_of_shards: 1
  shield.authc.realms:
    esusers:
      type: esusers
      order: 0
    native:
      type: native
      order: 1
    active_directory:
      type: active_directory
      order: 2
      domain_name: "{{ es_ldap_domain }}"
      url: "{{ es_ldap_url }}"
      unmapped_groups_as_roles: true

# ES plugins
es_plugins_reinstall: false
es_plugins:
  - plugin: license
  - plugin: shield
  - plugin: marvel-agent
  - plugin: mobz/elasticsearch-head
# ES users to create
es_users:
  - user: kibana4_server
    roles:
      - kibana4_server
  - user: "{{ instance_name }}_app"
    roles:
      - "{{ instance_name }}_app"
  - user: qlikview_app
    roles:
      - "{{ instance_name }}_app"

# ES roles to create
es_roles:
  - name: "{{ instance_name }}_app"
    cluster: ['all']
    indices:
      - { 'names': ['{{ instance_name }}_*'], 'privileges': ['all'] }
      - { 'names': ['.kibana*'], 'privileges': ['all'] }
  - name: my_kibana_user
    cluster: ['monitor']
    indices:
      - { 'names': ['*'], 'privileges': ['view_index_metadata', 'read'] }
      - { 'names': ['.kibana*'], 'privileges': ['all'] }

# Curator crons to run
es_curator_crons:
  - cron: "00 02 * * *"
    action_file: snapshot_previous_day.yml
```

Regards,
Carl
