### ISSUE TITLE
Proposal to Remove management of Java in Role

### ISSUE THREAD

**Issue by gingerwizard** [elastic/ansible-elasticsearch#268]
Currently we attempt to install java as well as refreshing certs - due to openjdk issues. Personally i feel our management of java is inadequate and there are superior roles for this. 

Either we enhance this component of the role or remove it entirely.  The former will add significant maintenance work and complexity for something that is not core to the roles purpose.  If we remove i would propose we check the environment and fail if it is not appropriately configured i.e. java8 installed for 5.x and certs working.

@jakommo @strootman @dliappis @barryib

**Comment by dliappis** [comment]
I am +1 on removing management of java in this role. This is a task better handled by a dedicated java role and this role is for installing elasticsearch, so I also agree with what @gingerwizard said i.e. just ensure the java env + certs are working and fail otherwise.

**Comment by barryib** [comment]
+1000. It's almost a [DOTADIW](http://dotadiw.com/), Do One Thing and Do It Well :nerd_face:

**Comment by strootman** [comment]
This role is already doing A LOT!!! I am in favor of removing it from this role, but still providing the functionality via external role.

Dependency can be handled in many different ways.
1. `ansible-galaxy install elastic.elasticsearch`
  * Dependencies automatically managed/installed via configuration in `meta/main.yml`
1. `ansible-galaxy install -r install_roles.yml`
  * A file could be supplied by this role for manual role installation
  * [Ansible Role Management](https://galaxy.ansible.com/intro#download)
1. Supplying playbooks

I'm ok with either of the first two. 


That being said, how should we proceed?
Should we discuss/establish criteria for role selection? (i.e. must refresh certs, JRE vs JDK)
Does anyone have java role candidates?

https://galaxy.ansible.com/geerlingguy/java/

**Comment by carlosfunk** [comment]
I've tried this successfully last night using the geerlingguy.java role:

```
vars:
  es_java_install: false
pre_tasks:
  - name: installing repo for Java 8 in Ubuntu
    apt_repository: repo='ppa:openjdk-r/ppa'
roles:
  - role: geerlingguy.java
    when: "ansible_os_family == 'Debian'"
    java_packages:
      - openjdk-8-jdk
  - { role: elasticsearch, es_instance_name: "node1"}
  ...
```
