### ISSUE TITLE
Ubuntu 14.04 - repetitive run triggers dpkg error - 2.4.3

### ISSUE THREAD

**Issue by bery** [elastic/ansible-elasticsearch#282]
When running my playbook for the second time, dpkg throws an error

```
fatal: [localhost]: FAILED! => {
    "cache_update_time": 1490874211,
    "cache_updated": false,
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false,
            "autoremove": false,
            "cache_valid_time": 86400,
            "deb": null,
            "default_release": null,
            "dpkg_options": "force-confdef,force-confold",
            "force": false,
            "install_recommends": null,
            "name": "elasticsearch=2.4.3",
            "only_upgrade": false,
            "package": [
                "elasticsearch=2.4.3"
            ],
            "purge": false,
            "state": "present",
            "update_cache": false,
            "upgrade": null
        },
        "module_name": "apt"
    },
    "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'elasticsearch=2.4.3'' failed: E: There are problems and -y was used without --force-yes\n",
    "stderr": "E: There are problems and -y was used without --force-yes\n",
    "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following packages were automatically installed and are no longer required:\n  linux-headers-3.13.0-113 linux-headers-3.13.0-113-generic\n  linux-image-3.13.0-113-generic\nUse 'apt-get autoremove' to remove them.\nThe following packages will be DOWNGRADED:\n  elasticsearch\n0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 0 not upgraded.\nNeed to get 0 B/27.2 MB of archives.\nAfter this operation, 0 B of additional disk space will be used.\n",
    "stdout_lines": [
        "Reading package lists...",
        "Building dependency tree...",
        "Reading state information...",
        "The following packages were automatically installed and are no longer required:",
        "  linux-headers-3.13.0-113 linux-headers-3.13.0-113-generic",
        "  linux-image-3.13.0-113-generic",
        "Use 'apt-get autoremove' to remove them.",
        "The following packages will be DOWNGRADED:",
        "  elasticsearch",
        "0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 0 not upgraded.",
        "Need to get 0 B/27.2 MB of archives.",
        "After this operation, 0 B of additional disk space will be used."
    ]
}
```
Playbook:
```
- hosts: elastic_servers
  become: yes
  become_user: root
  vars:
    es_plugins:
            - plugin: royrusso/elasticsearch-HQ
            - plugin: analysis-phonetic
            - plugin: analysis-icu
    es_plugins_reinstall: true
    es_config:
      network.publish_host: "{{ groups['elastic_servers'][0] }}"
      network.host: "{{ groups['elastic_servers'][0] }}"
      network.bind_host: "{{ groups['elastic_servers'][0] }}"
  roles:
      - ansible-elasticsearch
```

Do you have any ideas what could be causing this issue?
