### ISSUE TITLE
X-Pack directory creation skipped for role_mappings

### ISSUE THREAD

**Issue by rusnyder** [elastic/ansible-elasticsearch#290]
### Problem

When installing multiple instances on the same machine with x-pack security enabled and `es_role_mappings` defined, the second instance to be configured will fail setup because the security plays are incidentally dependent on the x-pack directory being created either by plugin install or by `es_roles` or `es_users` also being defined.

### Playbook

_NOTE: This playbook is a little funky in that it configures `es_role_mappings` but doesn't enable SSL.  This is because I wasn't particularly inclined to copy over my cert generation playbooks for the sake of creating valid certs, and even without enabling SSL the bug still manifests in the same way_

```yaml
---
- name: Elasticsearch Multi test - master on 9200
  hosts: localhost
  vars:
    es_scripts: true
    es_templates: true
    es_heap_size: "1g"
    es_api_port: 9200
    es_enable_xpack: true
    es_api_basic_auth_username: elastic
    es_api_basic_auth_password: changeme
    es_role_mapping:
      - cn=sample
  roles:
    - role: elasticsearch
      es_instance_name: "master"
      es_data_dirs: ["/opt/elasticsearch/master"]
      es_config:
        discovery.zen.ping.unicast.hosts: "localhost:9300"
        http.port: 9200
        transport.tcp.port: 9300
        node.data: false
        node.master: true
        bootstrap.memory_lock: true

- name: Elasticsearch Multi test - data on 9201
  hosts: localhost
  vars:
    es_scripts: true
    es_templates: true
    es_heap_size: "1g"
    es_api_port: 9201
    es_enable_xpack: true
    es_api_basic_auth_username: elastic
    es_api_basic_auth_password: changeme
    es_role_mapping:
      - cn=sample
  roles:
    - role: elasticsearch
      es_instance_name: "node1"
      es_data_dirs: "/opt/elasticsearch/data-1,/opt/elasticsearch/data-2"
      es_config:
        discovery.zen.ping.unicast.hosts: "localhost:9300"
        http.port: 9201
        transport.tcp.port: 9301
        node.data: true
        node.master: false
```

### Testing

I've also got this playbook checked in as a Kitchen test in my fork: https://github.com/rusnyder/ansible-elasticsearch/tree/role-mapping-xpack-dir-test

That test can be run with:

```bash
git clone https://github.com/rusnyder/ansible-elasticsearch elasticsearch
cd elasticsearch
git checkout role-mapping-xpack-dir-test
bundle install
ES_XPACK_LICENSE_FILE=/path/to/license.json bundle exec kitchen test role-mapping-xpack-dir-centos-7
```

### Solution

The logic that ensures that the `x-pack` dir exists is just pushed one playbook too deep.  It's pushed into a playbook that only gets invoked if `es_roles` or `es_users` are configured, but it also needs to execute for `role_mappings` (and for the PKI auth strategy we're using, we configure `role_mappings` and neither of the others for now)

PR will be coming shortly.
