### ISSUE TITLE
in Ubuntu Xenial, this installs version 2.4.3 instead of 5.1.2

### ISSUE THREAD

**Issue by pabloalbrecht** [elastic/ansible-elasticsearch#292]
Hi, 

(ubuntu xenial)

I have just run this ansible playblook: 
```
---
- hosts: elk_001
  roles:
    - role: medzin.oracle-jdk
    - role: elastic.elasticsearch
      es_instance_name: "node001"
      es_data_dirs: "/mnt/data-volume/elasticsearch/data"
      es_log_dir: "/mnt/data-volume/elasticsearch/logs"
      es_heap_size: 5g
      es_api_port: 9200

```
and when running 
```
curl -XGET "http://localhost:9200/?pretty"
```
I get the following output:
```
{
  "name" : "node001",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "bP2pO0CjTvu9eiwk_zsXnw",
  "version" : {
    "number" : "2.4.3",
    "build_hash" : "d38a34e7b75af4e17ead16f156feffa432b22be3",
    "build_timestamp" : "2016-12-07T16:28:56Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.2"
  },
  "tagline" : "You Know, for Search"
}
```

It seems that it installed the version 2.4.3 instead of the 5.1.2 as described in the README.md

I'd like to ideally install the 5.3.0, but adding `es_version: 5.3.0` doesn't seem to work
