### ISSUE TITLE
Ubuntu 16.04.2: stuck at "Wait for elasticsearch to startup"

### ISSUE THREAD

**Issue by Dextro** [elastic/ansible-elasticsearch#296]
Ansible is stuck at "Wait for elasticsearch to startup" and just times out.
Setup is Ubuntu 16.04.02

```
Playbook:
- name: Install and configure elasticsearch
  hosts: localhost
  remote_user: 'deploy'
  become: True
  roles:
    - role: elastic.elasticsearch
```

With just a single variable:
`es_instance_name: "node1"`

I can't figure out what goes wrong.
