### ISSUE TITLE
Stuck on task: "Wait for elasticsearch to startup"

### ISSUE THREAD

**Issue by aldee07** [elastic/ansible-elasticsearch#333]
Using this minimal playbook configuration/definition...

```
---
- name: ES
  hosts: local
  vars:
    es_start_service: true
  roles:
    - role: elasticsearch
      es_instance_name: "node1"
      es_config: { http.port: 9200 }
```
always ends up to a Connection Timeout problem. 

I also tried this suggestion https://discuss.elastic.co/t/ubuntu-16-04-ansible-elasticsearch-stuck-at-wait-for-elasticsearch-to-startup/83338/7 but to no luck.
