### ISSUE TITLE
How to add settings for GCE to elasticsearch.yml

### ISSUE THREAD

**Issue by svanschalkwyk** [elastic/ansible-elasticsearch#340]
Hi
This should be added to elasticsearch.yml:
```
cloud:
  gce:
      project_id: es-cloud
      zone: europe-west1-a
discovery:
      type: gce
```
Can it simply be appended to the end of elasticsearch.yml.j2? Or is there a cleaner way to add this?
Any help would be much appreciated.
