### ISSUE TITLE
Obsolete config template with ES 5.4.1

### ISSUE THREAD

**Issue by smougenot** [elastic/ansible-elasticsearch#344]
Environment : Vagrant box
OS/Box :  puppetlabs/centos-6.6-64-nocm

Playbook (from sample in the documentation) :
```
  roles:
    - {role: java }
    - role: elastic.elasticsearch
      vars:
        es_version: "5.4.1"
        es_instance_name: "log1"
        es_heap_size: "256m"
        es_enable_xpack: false
        network:
         host: "_eth0_"
        http:
         port: 9200
        transport:
         tcp:
          port: 9300
        node:
         data: true
         master: true
```

Error :
```
"Starting elasticsearch: Error: encountered environment variables that are no longer supported\nUse jvm.options or ES_JAVA_OPTS to configure the JVM\nES_HEAP_SIZE=256m: set -Xms256m and -Xmx256m in jvm.options or add \"-Xms256m -Xmx256m\" to ES_JAVA_OPTS\n[FAILED]\r\n"
```

Log :
```
RUNNING HANDLER [elastic.elasticsearch : restart elasticsearch] ****************
Wednesday 02 August 2017  17:18:53 +0200 (0:00:00.011)       0:00:36.880 ****** 
Running service
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/system/service.py
...
fatal: [vagrant_host]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "arguments": "", 
            "enabled": true, 
            "name": "log1_elasticsearch", 
            "pattern": null, 
            "runlevel": "default", 
            "sleep": null, 
            "state": "restarted"
        }
    }, 
    "msg": "Starting elasticsearch: Error: encountered environment variables that are no longer supported\nUse jvm.options or ES_JAVA_OPTS to configure the JVM\nES_HEAP_SIZE=256m: set -Xms256m and -Xmx256m in jvm.options or add \"-Xms256m -Xmx256m\" to ES_JAVA_OPTS\n[FAILED]\r\n"
}
```
