### ISSUE TITLE
Fails when disabling X-Pack Security

### ISSUE THREAD

**Issue by hatdropper1977** [elastic/ansible-elasticsearch#346]
I have the following YAML in the vars stanza of Ansible playbook:
```yaml
  vars:
    es_version: "5.5.1"
    es_heap_size: 2g
    es_enable_xpack: true
    es_xpack_features:
      - monitoring
      - graph
      - ml
```
 When I execute the playbook I get this message:
```syslog
[2017-08-02T20:43:27,758][INFO ][o.e.p.PluginsService ] [elk] no plugins loaded
```
I  would expect Ansible it to load **x-pack** due to the **es_enable_xpack** flag.

 Since I disable security (by virtue of [leaving it off the list](https://github.com/elastic/ansible-elasticsearch/blob/master/templates/elasticsearch.yml.j2) ) Ansible sets **xpack.security.enabled** to **false** and I get this error...
```syslog
java.lang.IllegalArgumentException: unknown setting [xpack.security.enabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
```
Trying a different approach - this fails as well:
```yamlroles:
    - { role: elasticsearch, es_instance_name: "elk" ,
    es_config: {
        node.name: "elk",
        cluster.name: "elk-centos",
        network.host: 0.0.0.0,
        http.port: 9200,
        transport.tcp.port: 9300,
        discovery.zen.ping.unicast.hosts: "localhost:9300",
        bootstrap.memory_lock: false,
        xpack.security.enabled: false,
        }
    }
  vars:
    es_version: "5.5.1"
    es_heap_size: 2g
    es_enable_xpack: true
    es_api_basic_auth_username: elastic
    es_api_basic_auth_password: changeme
```
That is, I get the same error, the plugin does not install and xpack.security.enabled crashes the system.
