### ISSUE TITLE
Can't have only native users

### ISSUE THREAD

**Issue by saudurehman** [elastic/ansible-elasticsearch#368]
<!

**Elasticsearch version**: 5.5.1

**Role version**:  (ea5a373)

**JVM version** (`1.8`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behaviour**:
If you try to create only native users and no file users the playbook fails.
**Playbook**:
```yaml
- hosts: localhost
  roles:
    - {
        role: elasticsearch,
        es_config: 
        { 
          "xpack.security.authc.realms.file1.type": "file",
          "xpack.security.authc.realms.file1.order": 1,
          "xpack.security.authc.realms.native1.type": "native",
          "xpack.security.authc.realms.native1.order": 0
        },
    es_instance_name: "security_node" }
  vars:
    es_heap_size: "1g"
    es_enable_xpack: true
    es_plugins:
      - plugin: ingest-geoip
    es_xpack_features:
      - security
      - alerting
    es_api_basic_auth_username: elastic
    es_api_basic_auth_password: changeme
    es_users:
      native:
        testUser:
          password: changeme
          roles:
            - kibana_user
```
**Provide logs from Ansible**:
TASK [elasticsearch : Ensure x-pack conf directory exists (file)] ****************************************************************************
task path: /Users/ElasticHome/Desktop/my/repos/ansible-elasticsearch/tasks/xpack/security/elasticsearch-security.yml:7
fatal: [ec2-52-201-145-56.compute-1.amazonaws.com]: FAILED! => {
    "failed": true,
    "msg": "The conditional check '(es_users is defined and es_users.file) or (es_roles is defined and es_roles.file is defined) or (es_role_mapping is defined)' failed. The error was: error while evaluating conditional ((es_users is defined and es_users.file) or (es_roles is defined and es_roles.file is defined) or (es_role_mapping is defined)): 'dict object' has no attribute 'file'\n\nThe error appears to have been in '/Users/ElasticHome/Desktop/my/repos/ansible-elasticsearch/tasks/xpack/security/elasticsearch-security.yml': line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n#Ensure x-pack conf directory is created if necessary\n- name: Ensure x-pack conf directory exists (file)\n  ^ here\n"
}
**ES Logs if irrelevant**:
