### ISSUE TITLE
Change password of reserved user

### ISSUE THREAD

**Issue by saudurehman** [elastic/ansible-elasticsearch#369]
<!

**Describe the feature**:
The playbook should allow to change passwords of reserved/default users.
**Playbook**
```yaml
- hosts: localhost
  roles:
    - {
        role: elasticsearch,
        es_config: 
        { 
          "xpack.security.authc.realms.file1.type": "file",
          "xpack.security.authc.realms.file1.order": 1,
          "xpack.security.authc.realms.native1.type": "native",
          "xpack.security.authc.realms.native1.order": 0
        },
    es_instance_name: "security_node" }
  vars:
    es_heap_size: "1g"
    es_enable_xpack: true
    es_plugins:
      - plugin: ingest-geoip
    es_xpack_features:
      - security
      - alerting
    es_api_basic_auth_username: elastic
    es_api_basic_auth_password: changeme
    es_users:
      file:
        kibana:
          password: changeme
          roles:
            - kibana_system
```
