### ISSUE TITLE
Elasticsearch service does not restart automatically after crash on systemd

### ISSUE THREAD

**Issue by mkaput** [elastic/ansible-elasticsearch#371]
**Elasticsearch version**: irrelevant

**Role version**:  5.5.1

**JVM version** (`java -version`): irrelevant

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 16.04

**Description of the problem including expected versus actual behaviour**:
[Systemd Unit template](https://github.com/elastic/ansible-elasticsearch/blob/ea5a373155e96dfc4941b2bec3920e7f76eb28de/templates/systemd/elasticsearch.j2) for Elasticsearch service does not contain
```ini
[Service]
Restart=always
```
entry, which means, that currently when service crashes, it is not restarted automatically.

**Playbook**:
irrelevant

**Provide logs from Ansible**:
irrelevant

**ES Logs if irrelevant**:
irrelevant

**Comment by jpcarey** [comment]
@mkaput the `Restart=always` is not in the default service provided by elasticsearch: https://github.com/elastic/elasticsearch/blob/v5.5.1/distribution/src/main/packaging/systemd/elasticsearch.service
I'd suggest requesting this upstream. Systemd uses override confs for changes that should persist regardless of package updates.

From command line (providing for reference, so you can customize your playbook to add the directory and create this single file): `systemctl edit elasticsearch.service` - this would create `/etc/systemd/system/elasticsearch.service.d/override.conf`. You would just add your customization
```
[Service]
Restart=always
```
then `systemctl daemon-reload` to refresh the unit files. You can check using `systemctl cat elasticsearch.service`.  

(the service created by this ansible playbook will use `nodeName_elasticsearch.service`)

**Comment by mkaput** [comment]
Didn't know about `systemctl edit`, thanks!

**Comment by mkaput** [comment]
In case anyone stumbles on this problem, this simple role does the job:

```yml
# roles/elasticsearch-restart/tasks/main.yml
---
- fail: msg="es_instance_name must be specified and cannot be blank"
  when: es_instance_name is not defined or es_instance_name == ''

- name: override Elasticsearch service unit config to restart after crash
  ini_file:
    path: "/etc/systemd/system/{{ es_instance_name }}_elasticsearch.service.d/override.conf"
    section: Service
    option: Restart
    value: always
    no_extra_spaces: yes
    mode: 644

- name: restart systemd & elastic service
  systemd:
    state: restarted
    daemon-reload: yes
    name: "{{ es_instance_name }}_elasticsearch"

# usage:
- role: elasticsearch-restart
  es_instance_name: "logs"
```
