### ISSUE TITLE
Java install fails - No package matching 'openjdk-8-jre-headless' is available

### ISSUE THREAD

**Issue by tomnewport** [elastic/ansible-elasticsearch#390]
**Elasticsearch version**: 5.x

**Role version**:  master/7714c92

**JVM version**: 8

**OS version**: Ubuntu 14.04

**Description of the problem including expected versus actual behaviour**:

When using role to install on Ubuntu 14.04, ansible fails with error: No package matching 'openjdk-8-jre-headless' is available

**Playbook**:

```yaml
- name: Simple Example
  hosts: vms
  remote_user: ---------
  roles:
    - role: elasticsearch
      es_instance_name: "node1"
  vars:
```

**Provide logs from Ansible**:

```
TASK [elasticsearch : Refresh java repo] ****************************************************************************************************************
ok: [---.---.---.---]

TASK [elasticsearch : Debian - Ensure Java is installed] ************************************************************************************************
fatal: [---.---.---.---]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'openjdk-8-jre-headless' is available"}
	to retry, use: -------------------/play.retry

PLAY RECAP **********************************************************************************************************************************************
---.---.---.---               : ok=16   changed=0    unreachable=0    failed=1   
```
