### ISSUE TITLE
Custom plugins cause non-idempotent behavior

### ISSUE THREAD

**Issue by edge-records** [elastic/ansible-elasticsearch#391]
**Elasticsearch version**
5.6.2

**Role version**:  (If using master please specify github sha)
n/a

**JVM version** (`java -version`):
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)

**OS version** (`uname -a` if on a Unix-like system):
Ubuntu 14.04

**Description of the problem including expected versus actual behaviour**:
***Observed behavior:***
I'm using this role to load my own custom Elasticsearch Plugin. This is what I see:
```
TASK [elastic.elasticsearch : Remove elasticsearch plugins] ****
changed: [mybox] => (item=Myplugin)

TASK [elastic.elasticsearch : Install elasticsearch plugins] ****
changed: [mybox] => (item={u'plugin': u'file:///path/to/Myplugin-1.0.4.zip'})
```
Where `Myplugin` is the name I've given it in `plugin-descriptor.properties`.  The ansible code from the plugins task `installed_plugins.stdout_lines | difference(es_plugins | json_query('[*].plugin'))` compares the name from plugin-descriptor against the URI of the zip file, which can't be the same.

This means elasticsearch uninstalls and reinstalls it at every ansible run, and therefore restarts the service every time.

***Expected behavior:***
Don't reinstall `Myplugin` at every ansible run

**Playbook**:
```
es_config:
  [...]
    es_plugins:
      - plugin: file:///path/to/Myplugin-1.0.4.zip
      - plugin: repository-s3
```

**Provide logs from Ansible**:
See above

**ES Logs if irrelevant**:

**Comment by SvenWoltmann** [comment]
This pull request fixes your problem: https://github.com/elastic/ansible-elasticsearch/pull/374

Basically it's sufficient to change only this one line of code: https://github.com/elastic/ansible-elasticsearch/pull/374/commits/0e1de2f1a583998a22e5e17c06ec6e0a39fcc358

Then you change your configuration to:
```
es_plugins:
  - plugin: Myplugin
    url: file:///path/to/Myplugin-1.0.4.zip
  - plugin: repository-s3
```

That's all.
