### ISSUE TITLE
Define a proxy for plugin installation

### ISSUE THREAD

**Issue by robin13** [elastic/ansible-elasticsearch#4]
Ability to define a proxy port like [this](https://github.com/elastic/puppet-elasticsearch#from-custom-url)

**Comment by barryib** [comment]
Hello, I have problem with proxy also. I'm going to work on this on our installation, so would like to know what direction to take in order to contribue back to the community.

So what do you think about these proposals:

1- Define proxy for all plugins installation at once
```
es_plugins_proxy_host: proxy.example.com
es_plugins_proxy_port: 8080
```
2- Define proxy for particular plugin
```
es_plugins:
  - plugin: license
  - plugin: marvel-agent
  - plugin: lmenezes/elasticsearch-kopf
    version: master
    proxy_host: proxy.example.com
    proxy_port: 8080
```
