### ISSUE TITLE
TASK [elasticsearch : Check if bootstrap password is set] fails due to use of instances

### ISSUE THREAD

**Issue by nilscant** [elastic/ansible-elasticsearch#420]
**Elasticsearch version**: 6.2

**Role version**:  d7a5af8c33c5adb3aeff5d9e2caba2e2f853cd4d

**JVM version** (`java -version`): n/a

**OS version** (`uname -a` if on a Unix-like system):
Linux elastic1 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behaviour**:
Ansible run fails:

```
TASK [elasticsearch : Check if bootstrap password is set] ************************************************
fatal: [elastic3]: FAILED! => {"changed": false, "cmd": ["/usr/share/elasticsearch/bin/elasticsearch-keystore", "list"], "delta": "0:00:00.095792", "end": "2018-02-07 15:53:18.289945", "msg": "non-zero return code", "rc": 1, "start": "2018-02-07 15:53:18.194153", "stderr": "/usr/share/elasticsearch/bin/elasticsearch-env: line 70: /etc/sysconfig/elasticsearch: No such file or directory", "stderr_lines": ["/usr/share/elasticsearch/bin/elasticsearch-env: line 70: /etc/sysconfig/elasticsearch: No such file or directory"], "stdout": "", "stdout_lines": []}
```

**Playbook**:
```
---
- hosts: elasticsearch
  roles:
  - elasticsearch
```

**Some variables**:
```
---
es_major_version: "6.x"
es_version: "6.2.0"
es_version_lock: true
es_restart_on_change: false
es_enable_xpack: true
es_xpack_features: ["alerting", "monitoring", "security"]
es_instance_name: es-01
```

The elasticsearch role removes **/etc/sysconfig/elasticsearch** in favor of instance-specific environment configuration files (eg /etc/sysconfig/es-01_elasticsearch). The **elasticsearch_keystore** script calls **elasticsearch_env**, which in turn tries to source the environment file at its default location:

**/usr/share/elasticsearch/bin/elasticsearch-env**"
```
[...]
source /etc/sysconfig/elasticsearch
[...]
```

**Task file**:
elasticsearch/tasks/xpack/security/elasticsearch-security.yml

**Task**:
```
- name: Check if bootstrap password is set 
  command: >
   {{es_home}}/bin/elasticsearch-keystore list
  register: list_keystore
  changed_when: False
  environment:
    ES_PATH_CONF: "{{ conf_dir }}"
  when:
    - (es_enable_xpack and '"security" in es_xpack_features') and (es_version | version_compare('6.0.0', '>'))
```

We could omit deleting **/etc/sysconfig/elasticsearch**, but then we may end up with invalid settings for the instance we wish to provision.

Perhaps it would be best to provide patched copies of **/usr/share/elasticsearch/bin/elasticsearch-keystore** and **elasticsearch-env** for each instance (eg: **/usr/share/elastsicsearch/bin/elasticsearch_{{ es_instance_name }}-keystore**) and call those instead?

The alternative would be to patch elasticsearch_env upstream so that it can accept an instance name as an optional parameter.
