### ISSUE TITLE
Support for setting JVM options

### ISSUE THREAD

**Issue by torfsen** [elastic/ansible-elasticsearch#448]
**Describe the feature**: As far as I understand, it's currently not possible to configure [JVM options](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/setting-system-settings.html#jvm-options) for the `elasticsearch` role -- at least the [`jvm.options` template](https://github.com/elastic/ansible-elasticsearch/blob/0179bd1eefa6d5c6358f3db29b9e2ad902625393/templates/jvm.options.j2) doesn't look like it.

I would like to set the [`es.enforce.bootstrap.checks` JVM option](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/bootstrap-checks.html#_forcing_the_bootstrap_checks), but it seems that this is currently not supported. Hence I suggest a way to set JVM options in general, e.g.

```
roles:
  - role: elasticsearch
    es_config: { ... }
    jvm_options:
        es.enforce.bootstrap.checks: true
```
