### ISSUE TITLE
Elastic plugins installation not idempotent in case of version upgrade and playbook crash

### ISSUE THREAD

**Issue by toadjaune** [elastic/ansible-elasticsearch#462]
## System configuration
**Elasticsearch version**: `6.3.0`

**Role version**: `6.3.0`

**JVM version** (`java -version`):
```
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):
```
Linux hostname 4.9.0-6-amd64 #1  SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
```

**Ansible version** : 
```
ansible 2.5.5
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]
```

## Problem description
When upgrading to a new ElasticSearch version, we need to reinstall the plugins for the new version.

The current version of the role does it, however, it relies on detecting that the installed ES version has changed during the _current_ run instead of detecting an incoherence. Meaning that in case of playbook interruption between the ES upgrade and the plugin installation, the second run won't upgrade the plugins, leaving ES in an unable to start state.

This can also happen if the package upgrade itself fails halfway through (that was my case), and if you then go and fix it manually on the target machine. (Obviously, the fact that this upgrade failed in the first place is a problem itself, but it should not have such consequences on idempotence)

## Reproduction steps
* Install elasticsearch on a machine with a given version (for example, `6.0.0`) with this role, and at least one plugin enabled
* Start to update to a newer version (for example, `6.1.0`) with this role, but interrupt the playbook immediately after the `Ensure elasticsearch is installed` task
* Re-run the playbook

You should now be in a state where the role sees everything as fine, and won't change anything, whereas ES won't start because of incompatible plugins

## Workaround
Basically anything that causes the role to change the state of the ES package will cause the next run to fix this issue. You can either manually downgrade it, or uninstall it on the target machine…

Manually setting the ansible `es_plugins_reinstall` variable to true should work as well, but I haven't tried it.

## Fix idea
I first thought to use the output of the following command : 
```
$ bin/elasticsearch-plugin list
x-pack
WARNING: plugin [x-pack] is incompatible with version [6.1.0]; was designed for version [6.0.0]
```
Which would be a great way to know which plugins need to be reinstalled.
It's a bit annoying that the warning is output to `stdout` together with the normal output, instead of being written to `stderr`, and that the return code is 0 regardless of current plugin compatibility ; but parsing such an output is definitely doable.

I was about to try and make a patch, but then I found this in the code : 
```
#List currently installed plugins. We have to list the directories as the list commmand fails if the ES version is different than the plugin version.
- name: Check installed elasticsearch plugins
  become: yes
  shell: "ls {{es_home}}/plugins {{list_command}}"
  register: installed_plugins
  changed_when: False
  ignore_errors: yes
  environment:
    CONF_DIR: "{{ conf_dir }}"
    ES_PATH_CONF: "{{ conf_dir }}"
    ES_INCLUDE: "{{ instance_default_file }}"
```

So, we're not using `elasticsearch-plugin list` because apparently, it fails in case of incompatible plugins. 
Except that it apparently doesn't, at least not since version `6.1.0`. Is this a new behaviour ? I couldn't find any documentation about this.

Either way, couldn't we leverage this command, one way or another ? Maybe even considering that a command failure means "invalid plugins, please wipe them all and reinstall them" ?
