### ISSUE TITLE
Role fails the second time running when es_plugins is set to an empty set

### ISSUE THREAD

**Issue by ServerNinja** [elastic/ansible-elasticsearch#466]
**Elasticsearch version**
6.3.0

**Role version**:  (If using master please specify github sha)
Using git tag: 6.3.0.1

**JVM version** (`java -version`):
```[vagrant@elastic1 ~]$ java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):
Centos7
`Linux elastic1 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behaviour**:
When specifying an empty set of es_plugins, the role installs elasticsearch just fine. But if you run the playbook a second time (on the same host), it fails due to a templating error (see below in ansible logs)

**Playbook**:
Please specify the full playbook used to reproduce this issue.

This assumes you have java installed on the host:
```
- hosts: elastic
  become: true

  vars:
    - app_env: vagrant

    ### Elasticsearch Ports ###
    - efk_es_transport_tcp_port: 9300
    - efk_es_http_port: 9200

    ### Elasticsearch version used ###
    - efk_es_url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.3.0.rpm
    - es_major_version: 6.3
    - es_version: 6.3.0

    ### Percentage of RAM that is used for Heap (JVM) ###
    - efk_percent_heap: 0.8

    ### Elastic Directories ###
    - es_data_dir: /var/lib/elasticsearch
    - es_log_dir: /opt/elasticsearch/logs
    - es_work_dir: /opt/elasticsearch/temp

    ### Elasticsearch install settings ###
    - es_restart_on_change: false
    - es_version_lock: false
    - es_start_service: true
    - es_java_install: false
    - efk_es_scripts: false
    - efk_es_templates: false
    - es_plugins_reinstall: false
    - es_plugins: {}

    - efk_es_cluster_name: poc

    - es_enable_xpack: true
    - es_api_basic_auth_username: admin
    - es_api_basic_auth_password: admin123

  pre_tasks:
    - set_fact:
        es_config:
          'discovery.zen.ping.unicast.hosts': ''

    - set_fact:
        es_config:
          'discovery.zen.ping.unicast.hosts': "{{ es_config['discovery.zen.ping.unicast.hosts'] + hostvars[item]['ansible_eth1'].ipv4.address }}:{{ efk_es_transport_tcp_port|string }},"
      with_items: "{{ groups['elastic'] }}"

    - name: Build Elasticsearch Cluster Config
      set_fact:
        es_config:
          'discovery.zen.ping.unicast.hosts': "{{ es_config['discovery.zen.ping.unicast.hosts'][:-1] }}"
          node.name: "{{ ansible_hostname }}"
          network.host: '0.0.0.0'
          cluster.name: "{{ efk_es_cluster_name }}"
          http.port: '{{ efk_es_http_port }}'
          transport.tcp.port: '{{ efk_es_transport_tcp_port }}'
          node.data: true
          node.master: true

  roles:
    - { role: ansible-elasticsearch,
        es_instance_name: "{{ app_env }}",
        es_use_repository: false,
        es_custom_package_url: '{{ efk_es_url }}',
        es_heap_size: '{{ (ansible_memtotal_mb * efk_percent_heap)|round|int|string }}m',
      }
```

**Provide logs from Ansible**:
```
TASK [ansible-elasticsearch : Check installed elasticsearch plugins] ***********
task path: /Users/reed/src/bluescape/ansible-infrastructure/galaxy_roles/ansible-elasticsearch/tasks/elasticsearch-plugins.yml:17
fatal: [elastic1]: FAILED! => {"changed": false, "cmd": "ls /usr/share/elasticsearch/plugins | grep -vE 'x-pack'", "delta": "0:00:00.005420", "end": "2018-07-03 14:35:18.138187", "failed": true, "rc": 1, "start": "2018-07-03 14:35:18.132767", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
...ignoring

TASK [ansible-elasticsearch : set fact plugins_to_remove to install_plugins.stdout_lines] ***
task path: /Users/reed/src/bluescape/ansible-infrastructure/galaxy_roles/ansible-elasticsearch/tasks/elasticsearch-plugins.yml:29
skipping: [elastic1] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}

TASK [ansible-elasticsearch : set fact plugins_to_remove to delete plugins installed but not listed in es_plugins] ***
task path: /Users/reed/src/bluescape/ansible-infrastructure/galaxy_roles/ansible-elasticsearch/tasks/elasticsearch-plugins.yml:34
ok: [elastic1] => {"ansible_facts": {"plugins_to_remove": []}, "changed": false}

TASK [ansible-elasticsearch : set fact plugins_to_install to es_plugins] *******
task path: /Users/reed/src/bluescape/ansible-infrastructure/galaxy_roles/ansible-elasticsearch/tasks/elasticsearch-plugins.yml:39
skipping: [elastic1] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}

TASK [ansible-elasticsearch : set fact to plugins_to_install to those in es_config but not installed] ***
task path: /Users/reed/src/bluescape/ansible-infrastructure/galaxy_roles/ansible-elasticsearch/tasks/elasticsearch-plugins.yml:44
fatal: [elastic1]: FAILED! => {"failed": true, "msg": "Unexpected templating type error occurred on ({{ es_plugins | json_query('[*].plugin') | difference(installed_plugins.stdout_lines) | default([]) }}): 'NoneType' object is not iterable"}
	to retry, use: --limit @/Users/reed/.ansible-retry/elastic_xpac_poc.retry

PLAY RECAP *********************************************************************
elastic1                   : ok=43   changed=0    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```
