### ISSUE TITLE
xpack.security.enabled: false twice in elasticsearch.yml when xpack.security.enabled: false

### ISSUE THREAD

**Issue by svanschalkwyk** [elastic/ansible-elasticsearch#477]
Bug report 
Elasticsearch version: 6.3.1
Role version 
JVM version: Oracle Java 8
OS version: 3.10.0-862.el7.x86_64 #1  SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux Centos 7

Description of the problem including expected versus actual behaviour:
When xpack.security.enables: false in playbook, elasticsearch.yml contains the line twice, causing ES startup to fail.
Issue seems to be here: 
```
{% if es_enable_xpack %}
{% if not "security" in es_xpack_features %}
xpack.security.enabled: false
{% endif %}
```
So one would have to include
```
 - security 
```
in xpack features, and disable it in
```
xpack.security.enabled: false
```
or not include it and remove 
```
xpack.security.enabled: false
```
from the playbook.

Playbook:
```
      xpack.security.authc.realms.file1.type: "file"
      xpack.security.authc.realms.file1.order: 1
      xpack.security.authc.realms.native1.type: "native"
      xpack.security.authc.realms.native1.order: 0
      xpack.security.enabled: false
      xpack.security.audit.enabled: false
      xpack.security.authc.accept_default_password: true
      xpack.monitoring.collection.enabled: true
    es_enable_xpack: true
    es_xpack_license: "{{ license }}"
    es_xpack_custom_url: "https://artifacts.elastic.co/downloads/packs/x-pack/x-pack-{{ es_version }}.zip"      
    es_xpack_features: 
      - alerting
      - monitoring
      - graph
      - ml      
#      - security
```

Provide logs from Ansible:

elasticsearch.yml:
```
bootstrap.memory_lock: true
cluster.name: RRD
discovery.zen.minimum_master_nodes: '0'
discovery.zen.ping.unicast.hosts:
- cxxxxxxxxxxxxx.com
http.port: '9200'
network.bind_host: _site_
network.host: _site_
network.publish_host: ' _site_'
node.data: 'true'
node.ingest: 'true'
node.master: 'true'
transport.tcp.port: '9300'
xpack.monitoring.collection.enabled: true
xpack.security.audit.enabled: false
xpack.security.authc.accept_default_password: true
xpack.security.authc.realms.file1.order: 1
xpack.security.authc.realms.file1.type: file
xpack.security.authc.realms.native1.order: 0
xpack.security.authc.realms.native1.type: native

xpack.security.enabled: true

node.name: cxxxxxxxxxxxxxxxxxxxx
#################################### Paths ####################################
# Path to directory containing configuration (this file and logging.yml):
path.data: /opt/elasticsearch/data/cxxxxxxxxxxxxxxxxx
path.logs: /var/log/elasticsearch/cxxxxxxxxxxxxxxxxxxx
action.auto_create_index: true

xpack.security.enabled: false
```

**Comment by patsevanton** [comment]
SimpleExample.yaml 
```
- name: Simple Example
  hosts: node1
  roles:
    - role: elastic.elasticsearch
      vars:
        es_xpack_features: false
        es_instance_name: "node1"
```

```
TASK [elastic.elasticsearch : fail when api credentials are not declared when using security] **************************************************
fatal: [node1]: FAILED! => {}

MSG:

The conditional check 'es_enable_xpack and ("security" in es_xpack_features) and es_api_basic_auth_username is not defined and es_api_basic_auth_password is not defined' failed. The error was: Unexpected templating type error occurred on ({% if es_enable_xpack and ("security" in es_xpack_features) and es_api_basic_auth_username is not defined and es_api_basic_auth_password is not defined %} True {% else %} False {% endif %}): argument of type 'bool' is not iterable

The error appears to have been in '/home/user/.ansible/roles/elastic.elasticsearch/tasks/elasticsearch-parameters.yml': line 29, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

#Check if working with security we have an es_api_basic_auth_username and es_api_basic_auth_username - otherwise any http calls wont work
- name: fail when api credentials are not declared when using security
  ^ here

```
