### ISSUE TITLE
configure roles mappings via API

### ISSUE THREAD

**Issue by andyb-elastic** [elastic/ansible-elasticsearch#505]
Currently this playbook can configure roles through the [role APIs](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/security-api.html#security-role-apis), but can only configure role mappings through the role_mapping.yml file and not the [role mapping APIs](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/security-api.html#security-role-mapping-apis). It would be helpful for users who do not use the mapping file, or users of the SAML realm (which only supports configuring role mappings through the API) to be able to do that with this playbook

**Comment by abraxxa** [comment]
I've implemented this in our playbook:

```
tasks:
- name: set role mappings
      uri:
        url: https://{{es_api_host}}:{{es_api_port}}/_xpack/security/role_mapping/{{item.key}}
        method: POST
        body_format: json
        body: "{{ item.value | to_json }}"
        status_code: 200
        user: "{{es_api_basic_auth_username}}"
        password: "{{es_api_basic_auth_password}}"
        force_basic_auth: yes
      #no_log: True
      run_once: True
      with_dict: "{{ es_role_mappings | default({}) }}"


vars:
  es_role_mappings:
      es-admins:
        enabled: true
        roles:
          - superuser
        rules:
          all:
            - field:
                realm.name : "AD"
            - field:
                groups:
                  - "CN=Elasticsearch Admins,OU=Groups,DC=example,DC=org"
      es-users:
        enabled: true
        roles:
          - kibana_user
          - monitoring_user
          - reporting_user
        rules:
          all:
            - field:
                realm.name : "AD"
            - field:
                groups:
                  - "CN=Elasticsearch Users,OU=Groups,DC=example,DC=org"
                  - "CN=Elasticsearch Power Users,OU=Groups,DC=example,DC=org"
```
