### ISSUE TITLE
 Activate ES license (with security authentication) : urlopen error [Errno 111] Connection refused

### ISSUE THREAD

**Issue by svanschalkwyk** [elastic/ansible-elasticsearch#507]
Elasticsearch version: 6.4.2

Verified that in:
```
 - name: Activate ES license (with security authentication)
      uri:
        method: PUT
        url: "http://{{es_api_host}}:{{es_api_port}}/_xpack/license?acknowledge=true"
        user: "{{es_api_basic_auth_username}}"
        password: "{{es_api_basic_auth_password}}"
        body_format: json
        force_basic_auth: yes
        body: "{{ es_xpack_license }}"
        return_content: yes
      register: license_activated
      no_log: false
      when: "'security' in es_xpack_features"
      failed_when: >
        license_activated.status != 200 or
        license_activated.json.license_status is not defined or
        license_activated.json.license_status != 'valid'  
```

The variables  "{{es_api_basic_auth_username}}" and  "{{es_api_basic_auth_password}}"
are being passed. Yet, the call fails.

Provide logs from Ansible:
```
TASK [elastic.elasticsearch : Activate ES license (with security authentication)                                                         ] ***
fatal: [rrlnx-cp-elsp1.rrd.com]: FAILED! => {"changed": false, "content": "", "f                                                         ailed_when_result": true, "msg": "Status code was -1 and not [200]: Request fail                                                         ed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "statu                                                         s": -1, "url": "http://10.79.148.109:9200/_xpack/license?acknowledge=true"}
```
