### ISSUE TITLE
Unable to upgrade Elasticsearch version

### ISSUE THREAD

**Issue by pkaramol** [elastic/ansible-elasticsearch#536]
**Elasticsearch version**
`6.4.2`

**Role version**:  (If using master please specify github sha)

```
cat roles/requirements.yml
- src: elastic.elasticsearch
  version: 6.4.0

```
**JVM version** (`java -version`):

```
 java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
```

**OS version** (`uname -a` if on a Unix-like system):
```
$ uname -a
Linux master01-elastic 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Description of the problem including expected versus actual behaviour**:

I installed without specifying `es_version` in my playbooks.

So now I have 

{
  "name" : "master01-elastic",
  "cluster_name" : "local-stg-cluster",
  "cluster_uuid" : "lb88tnVBQxOpXo22JAMR9Q",
  "version" : {
    "number" : "6.3.0",
    "build_flavor" : "default",
    "build_type" : "rpm",
    "build_hash" : "424e937",
    "build_date" : "2018-06-11T23:38:03.357887Z",
    "build_snapshot" : false,
    "lucene_version" : "7.3.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

I am trying to upgrade to `6.4.2` which is the desired version and it fails

**Playbook**:
Please specify the full playbook used to reproduce this issue.

**Provide logs from Ansible**:

```
TASK [elastic.elasticsearch : Detect if es_version is before X-Pack was open and included] ************************************************************************************************************************
Monday 11 February 2019  12:17:44 +0200 (0:00:00.057)       0:00:05.325 ******* 
fatal: [master01-elastic]: FAILED! => 
  msg: |-
    The conditional check 'es_version | version_compare('6.3.0', '<')' failed. The error was: An unhandled exception occurred while templating '{{ es_version }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ es_version }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ es_version }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ es_version }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ es_version }}'.
  (this message goes on the same several times)
```
    The error appears to have been in '/home/pkara/Workspace/gitlab/ansible-elastic/roles/elastic.elasticsearch/tasks/compatibility-variables.yml': line 18, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: Detect if es_version is before X-Pack was open and included
      ^ here

First time I run the plays was with `es_version_lock: true` but now setting it to `false` does not help either.

**Comment by Crazybus** [comment]
Hi Pantelis!

This looks like a weird one.

> **Playbook**:
> Please specify the full playbook used to reproduce this issue.

Could you add in these details please? 

And also the ansible version you are using since this smells like an ansible bug.

**Comment by pkaramol** [comment]
```
$ ansible --version
ansible 2.7.5
  config file = /home/pkara/Workspace/gitlab/ansible-elastic/ansible.cfg
  configured module search path = [u'/home/pkara/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

```
  - hosts: all
    gather_facts: True

  
  - name: Set up Elasticsearch Master Nodes
    import_playbook: masters.yml


  - name: Set up Elasticsearch Data Nodes
    import_playbook: data.yml
```


```
  - hosts: masters

    tasks:

    - name: Elasticsearch Master Configuration
      import_role:
          name: elastic.elasticsearch
      vars:
        es_version: "{{ es_version }}"
        es_instance_name: "{{ ansible_hostname }}"
        es_data_dirs:
          - "{{ data_dir }}"
        es_log_dir: "/opt/elasticsearch/logs"
        es_config:
          node.name: "{{ ansible_hostname }}"
          cluster.name: "{{ cluster_name }}"
          discovery.zen.ping.unicast.hosts: "{% for host in groups['masters'] -%}{{ hostvars[host]['ansible_ens33']['ipv4']['address'] }}:9300{% if not loop.last %},{% endif %}{%- endfor %}"
          http.port: 9200
          transport.tcp.port: 9300
          node.data: false
          node.master: true
          bootstrap.memory_lock: true
          network.host: '{{ ansible_facts["ens33"]["ipv4"]["address"] }}'
          discovery.zen.minimum_master_nodes: 1
        es_xpack_features: []
        es_scripts: false
        es_templates: false
        es_version_lock: false
        es_heap_size: 2g
        es_api_port: 9200
```


```
  - hosts: data

    tasks:

    - name: Elasticsearch Data Configuration
      import_role:
          name: elastic.elasticsearch
      vars:
        es_version: "{{ es_version }}"
        es_instance_name: "{{ ansible_hostname }}"
        es_data_dirs:
          - "{{ data_dir }}"
        es_log_dir: "/opt/elasticsearch/logs"
        es_config:
          node.name: "{{ ansible_hostname }}"
          cluster.name: "{{ cluster_name }}"
          discovery.zen.ping.unicast.hosts: "{% for host in groups['masters'] -%}{{ hostvars[host]['ansible_ens33']['ipv4']['address'] }}:9300{% if not loop.last %},{% endif %}{%- endfor %}"
          http.port: 9200
          transport.tcp.port: 9300
          node.data: true
          node.master: false
          bootstrap.memory_lock: true
          network.host: '{{ ansible_facts["ens33"]["ipv4"]["address"] }}'
          discovery.zen.minimum_master_nodes: 1
        es_xpack_features: []
        es_scripts: false
        es_templates: false
        es_version_lock: false
        es_heap_size: 6g
        es_api_port: 9200


```

`group_vars/all/main.yml`


```
  cluster_name: local-stg-cluster
  data_dir: /elastic_data
  es_version: "6.4.2"
```
