### ISSUE TITLE
_es_config_ does not support the long configuration value.

### ISSUE THREAD

**Issue by worapojc** [elastic/ansible-elasticsearch#549]
**Elasticsearch version**
6.6.0

**Role version**:  (If using master please specify github sha)
0ccf608

**JVM version** (`java -version`):
1.8

**OS version** (`uname -a` if on a Unix-like system):
Amazon Linux

**Description of the problem including expected versus actual behaviour**:
_es_config_ does not support the long configuration value.
searchguard.nodes_dn:
    - CN=10.49.*,OU=Technology Development,O=Refinitiv Company\, Inc.,DC=Service Excellence,DC=Service Tools,C=US

The output in elasticsearcy.yml is ...

> searchguard.authcz.admin_dn:
>\- CN=Compass Administrator,OU=Technology Development,O=Refinitiv Company\, Inc.,DC=Service
>           Excellence,DC=Service Tools,C=US

It cuts "Excellence" to the new line.

**Playbook**:
Please specify the full playbook used to reproduce this issue.

**Provide logs from Ansible**:

**ES Logs if relevant**:

**Comment by Crazybus** [comment]
Hi Worapoj!

Could you please add your configuration in a code block? Makes it much easier to see newlines/tabs/spacing that could be causing this issue.

Talking about doing it like this:

```
es_config:
  example: true
```

This role doesn't do anything special with the yaml. It just inserts it. Can you try adding quotes around your string? I think that might be what is causing the new line to occur here. 

https://github.com/elastic/ansible-elasticsearch/blob/509a91878f5cc1c1d482eb6037bfa9f0fc08f417/templates/elasticsearch.yml.j2#L2-L4

**Comment by worapojc** [comment]
> es_config:
>       cluster.name: "{{ cluster_name }}"
>       network.bind_host:
>       - _local:ipv4_
>       - _site:ipv4_
>       network.publish_host: _site:ipv4_
>       discovery.zen.ping.unicast.hosts: "{{ groups['master-aws'] }}"
>       discovery.zen.minimum_master_nodes: "{{ minimum_master_nodes }}"
>       node.data: "{{ es_node_type.data }}"
>       node.master: "{{ es_node_type.master }}"
>       node.ingest: "{{ es_node_type.ingest }}"
>       bootstrap.memory_lock: false
>       xpack.security.enabled: false
>       xpack.monitoring.enabled: true
>       xpack.monitoring.exporters:
>         id1:
>           type: http
>           host: "{{ groups['monitor-aws'] }}"
>       http.port: "{{ http_port }}"
>       searchguard.ssl.transport.pemcert_filepath: "{{ansible_default_ipv4.address}}.pem"
>       searchguard.ssl.transport.pemkey_filepath: "{{ansible_default_ipv4.address}}.key"
>       searchguard.ssl.transport.pemkey_password: compass
>       searchguard.ssl.transport.pemtrustedcas_filepath: root-ca.pem
>       searchguard.ssl.transport.enforce_hostname_verification: false
>       searchguard.ssl.transport.resolve_hostname: false
>       searchguard.ssl.http.enabled: true
>       searchguard.ssl.http.pemcert_filepath: "{{ansible_default_ipv4.address}}.pem"
>       searchguard.ssl.http.pemkey_filepath: "{{ansible_default_ipv4.address}}.key"
>       searchguard.ssl.http.pemkey_password: compass
>       searchguard.ssl.http.pemtrustedcas_filepath: root-ca.pem
>       searchguard.nodes_dn:
>         - 'CN=10.49.*,OU=Technology Development,O=Refinitiv Company\, Inc.,DC=Service Excellence,DC=Service Tools,C=US'
>       searchguard.authcz.admin_dn:
>         - 'CN=Compass Administrator,OU=Technology Development,O=Refinitiv Company\, Inc.,DC=Service Excellence,DC=Service Tools,C=US'
>       searchguard.audit.type: internal_elasticsearch
>       searchguard.check_snapshot_restore_write_privileges: true
>       searchguard.restapi.roles_enabled:

The issue is **to_nice_yaml**. I manually changed it to **to_yaml** and it works fine.

**Comment by Crazybus** [comment]
Can you try posting your config again please? You need to do it with three back ticks.

    ```
    insert yaml config
    ```

**Comment by worapojc** [comment]
Here...

```
es_config:
      cluster.name: "{{ cluster_name }}"
      network.bind_host:
      - _local:ipv4_
      - _site:ipv4_
      network.publish_host: _site:ipv4_
      discovery.zen.ping.unicast.hosts: "{{ groups['master-aws'] }}"
      discovery.zen.minimum_master_nodes: "{{ minimum_master_nodes }}"
      node.data: "{{ es_node_type.data }}"
      node.master: "{{ es_node_type.master }}"
      node.ingest: "{{ es_node_type.ingest }}"
      node.attr.box_type: "{{ es_data_node.box_type }}"
      bootstrap.memory_lock: false
      xpack.security.enabled: false
      xpack.monitoring.enabled: true
      xpack.monitoring.exporters:
        id1:
          type: http
          host: "{{ groups['monitor-aws'] }}"
      http.port: "{{ http_port }}"
      searchguard.ssl.transport.pemcert_filepath: "{{ansible_default_ipv4.address}}.pem"
      searchguard.ssl.transport.pemkey_filepath: "{{ansible_default_ipv4.address}}.key"
      searchguard.ssl.transport.pemkey_password: compass
      searchguard.ssl.transport.pemtrustedcas_filepath: root-ca.pem
      searchguard.ssl.transport.enforce_hostname_verification: false
      searchguard.ssl.transport.resolve_hostname: false
      searchguard.ssl.http.enabled: true
      searchguard.ssl.http.pemcert_filepath: "{{ansible_default_ipv4.address}}.pem"
      searchguard.ssl.http.pemkey_filepath: "{{ansible_default_ipv4.address}}.key"
      searchguard.ssl.http.pemkey_password: compass
      searchguard.ssl.http.pemtrustedcas_filepath: root-ca.pem
      searchguard.nodes_dn:
        - 'CN=10.49.*,OU=Technology Development,O=Refinitiv Company\, Inc.,DC=Service Excellence,DC=Service Tools,C=US'
      searchguard.authcz.admin_dn:
        - 'CN=Compass Administrator,OU=Technology Development,O=Refinitiv Company\, Inc.,DC=Service Excellence,DC=Service Tools,C=US'
      searchguard.audit.type: internal_elasticsearch
      searchguard.check_snapshot_restore_write_privileges: true
      searchguard.restapi.roles_enabled:
        - 'sg_all_access'
```
