### ISSUE TITLE
Add the ability to deploy a cluster of master nodes for v7.1

### ISSUE THREAD

**Issue by manuasir** [elastic/ansible-elasticsearch#583]
Hello,

Since Elastic v7 was released, the way to deploy a cluster of master nodes changed and now is required a [bootstrap phase](https://www.elastic.co/guide/en/elasticsearch/reference/current/discovery-settings.html) so the nodes can join. This behavior requires a `cluster.initial_master_nodes` option that I cannot see in this repository. I'd also like to know _how_ it is supposed to be deployed if I'd like to have, for example, three master nodes. The main question is: should every master node have that option? How could I distinguish between the 'bootstrap node' and the others? Until I know, we have to know every master node _previosly_. How can this be approached with Ansible?

Thanks, team!

**Comment by broferek** [comment]
To define the option, we can just add the option under es_config variable. This will deploy the option into elasticsearch.yml config file.

`es_config:
    cluster.initial_master_nodes: 
      - master-node-a
      - master-node-b
      - master-node-c
`

**Comment by manuasir** [comment]
Hello @broferek ,

Thanks for your response. I still have this doubt: how could I know the IP or the hostname of each node _before_? Maybe the master node which performs the bootstrap is deployed in the first place. How could I distinguish between a master node and a master `bootstrap` node? 

Appreciated

**Comment by broferek** [comment]
I can't answer these ones as I'm still in the process of migrating a 6.8 cluster to 7.1.1 and I'm also having issues with this setting. I'll post there if I find a working solution

**Comment by manuasir** [comment]
Alright @broferek , I'll keep an eye out for this issue. Thanks

**Comment by manuasir** [comment]
Hello again @broferek ,

Just in case this may help you. I implemented the following variables to my roles:

> `defaults/main.yml`
```
elasticsearch_bootstrap_node: false
elasticsearch_master_candidate: false
elasticsearch_cluster_nodes:
  - 127.0.0.1
elasticsearch_xpack_security: false
```

And I use them in my playbook like this. For deploying three master nodes:

```
- hosts: 172.16.0.161
  roles:
    - {role: ../roles/elastic-stack/ansible-elasticsearch, elasticsearch_network_host: '172.16.0.161', elasticsearch_bootstrap_node: true, elasticsearch_cluster_nodes: ['172.16.0.162','172.16.0.163','172.16.0.161']}

- hosts: 172.16.0.162
  roles:
    - {role: ../roles/elastic-stack/ansible-elasticsearch, elasticsearch_network_host: '172.16.0.162', elasticsearch_master_candidate: true, elasticsearch_cluster_nodes: ['172.16.0.162','172.16.0.163','172.16.0.161']}

- hosts: 172.16.0.163
  roles:
    - {role: ../roles/elastic-stack/ansible-elasticsearch, elasticsearch_network_host: '172.16.0.163', elasticsearch_master_candidate: true, elasticsearch_cluster_nodes: ['172.16.0.162','172.16.0.163','172.16.0.161']}
```

And I have a template that would render the proper `elasticsearch.yml` according to the logic:
```

cluster.name: {{ elasticsearch_cluster_name }}
node.name: {{ elasticsearch_node_name }}
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
bootstrap.memory_lock: true
network.host: {{ elasticsearch_network_host }}

{% if single_node %}
discovery.type: single-node
{% elif elasticsearch_bootstrap_node %}
node.master: true
cluster.initial_master_nodes: 
{% for item in elasticsearch_cluster_nodes %}
  - {{ item }}
{% endfor %}
{% elif elasticsearch_master_candidate %}
node.master: true
discovery.seed_hosts:
{% for item in elasticsearch_cluster_nodes %}
  - {{ item }}
{% endfor %}
{% endif %}
```

It actually works fine, I hope that helps.
