### ISSUE TITLE
Support the new secure_password for xpack notifications 

### ISSUE THREAD

**Issue by MikeBairdRocks** [elastic/ansible-elasticsearch#592]
**Describe the feature**:
when es_mail_config.pass is defined should know the elastic version and generate the secure_password in the keystore if >=7.0.

Docs:
- [Email Notification Settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/notification-settings.html#email-notification-settings)
- [Security Settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/secure-settings.html)

Also leave out the pass in [elasticsearch.yml.j2](https://github.com/elastic/ansible-elasticsearch/blob/master/templates/elasticsearch.yml.j2) since this will prevent 7 from starting with an invalid attribute setting.

Some sudo code:
```yaml
- name: Create Smtp password for notifications
  become: yes
  shell: echo "{{es_mail_config['pass']}}" | {{es_home}}/bin/elasticsearch-keystore add -x 'xpack.notification.email.account.{{ es_mail_config['account'] }}.smtp.secure_password'
  when:
    - es_mail_config['pass'] is defined and list_keystore is defined
  environment:
    ES_PATH_CONF: "{{ es_conf_dir }}"
  no_log: true
```

**Comment by Crazybus** [comment]
Makes a lot of sense. Since there are other secure settings besides this I think it would be a lot cleaner to instead implement a way to populate the keystore in a generic way. So instead of hard-coding it for this specific value just having a way to add files and strings to the keystore in a generic way like:

```
es_keystore:
  files:
    keystore_key: /path/to/file
  strings:
    xpack.notification.email.account.{{ es_mail_config['account'] }}.smtp.secure_password: {{ password_from_somwhere_secure }}
```
```
