### ISSUE TITLE
Add shield support

### ISSUE THREAD

**Issue by barryib** [elastic/ansible-elasticsearch#62]
I would like to add shield support, and I was wondering how we can structure things like variables and templates.

Here are my proposals:

**Dicts structure:**

```
es_license: my_vaulted_private_and_secret_license
es_users:
  - user: bob
    password: my_vaulted_secret_password
    role: user

es_role_mapping:
  - admin:
      - "cn=admins,dc=example,dc=com"
  - user:
      - "cn=users,dc=example,dc=com"
      - "cn=other-users,dc=example,dc=com"
```
or this structure (I personally prefer this one):

```
es_license: my_vaulted_private_and_secret_license
es_shield:
  - users:
      - user: bob
        password: my_vaulted_secret_password
        role: user
  - role_mapping:
      - admin:
        - "cn=admins,dc=example,dc=com"
      - user:
        - "cn=users,dc=example,dc=com"
        - "cn=other-users,dc=example,dc=com"
```

**Templates structure:**

Add these following templates to configure shield's roles and role mappings. For the main configuration, we'll use the `es_config` object.
```
+-- templates
|   +-- ...
|   +-- shield
|   |  +-- role_mapping.yml.j2
|   |  +-- roles.yml.j2
```

Do you have any suggestion or preference on how we should add this feature?
