### ISSUE TITLE
master not discovered yet: have discovered

### ISSUE THREAD

**Issue by patsevanton** [elastic/ansible-elasticsearch#627]
**Elasticsearch version**
7.4.1-1

**JVM version** (`java -version`):
/usr/share/elasticsearch/jdk/bin/java -version
openjdk version "13" 2019-09-17
OpenJDK Runtime Environment AdoptOpenJDK (build 13+33)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13+33, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system):
CentOS 7.6.1810

**Playbook**:
Please specify the full playbook used to reproduce this issue.
```
- hosts: master_node
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "10g"
    es_config:
      cluster.name: "test-cluster"
      discovery.seed_hosts: "172.26.9.41:9300,172.26.9.42:9300,172.26.9.43:9300"
      http.port: 9200
      node.data: false
      node.master: true
      bootstrap.memory_lock: false
    es_plugins:
     - plugin: ingest-attachment

- hosts: data_node
  roles:
    - role: elastic.elasticsearch
  vars:
    es_data_dirs:
      - "/opt/elasticsearch"
    es_config:
      cluster.name: "test-cluster"
      discovery.seed_hosts: "172.26.9.41:9300,172.26.9.42:9300,172.26.9.43:9300"
      http.port: 9200
      node.data: true
      node.master: false
      bootstrap.memory_lock: false
    es_plugins:
      - plugin: ingest-attachment

```
**Provide logs from Ansible**:
Ansible log dont have errors.
**ES Logs if relevant**:
```[2019-11-02T14:19:52,941][WARN ][o.e.c.c.ClusterFormationFailureHelper] [172.26.9.41] master not discovered yet: have discovered [{172.26.9.41}{CKxINSJUQJ6mPZGjYJ9weg}{PoLlBsflQHm56Tt3vQ1_ug}{127.0.0.1}{127.0.0.1:9300}{dil}{ml.machine_memory=33566568448, xpack.installed=true, ml.max_open_jobs=20}]; discovery will continue using [172.26.9.41:9300, 172.26.9.42:9300, 172.26.9.43:9300] from hosts providers and [] from last-known cluster state; node term 0, last-accepted version 0 in term 0```

Inventory
```
[master_node]
172.26.9.41
172.26.9.42
172.26.9.43
[data_node]
172.26.9.41
172.26.9.42
172.26.9.43
```

I can not find initial_master_nodes in ansible-elasticsearch repository

**Comment by Gurpartap** [comment]
Setting `cluster.initial_master_nodes` should work as such:

```yaml
cluster.initial_master_nodes: "172.26.9.41,172.26.9.42,172.26.9.43"
```
or using inventory hostvars:
```yaml
cluster.initial_master_nodes: "{{ groups.master_node | map('extract', hostvars, 'private_ip_address') | list }}"
```

**Comment by patsevanton** [comment]
Inventory
```
[master_node]
172.26.9.59
172.26.9.6
172.26.9.60
[data_node]
172.26.9.59
172.26.9.6
172.26.9.60
```
Playbook:
```
- hosts: master_node
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "10g"
    es_config:
      cluster.name: "test-cluster"
      cluster.initial_master_nodes: "{{ groups.master_node | map('extract', hostvars, 'private_ip_address') | list }}"
      discovery.seed_hosts: "172.26.9.59:9300,172.26.9.6:9300,172.26.9.60:9300"
      http.port: 9200
      node.data: false
      node.master: true
      bootstrap.memory_lock: false
    es_plugins:
     - plugin: ingest-attachment

- hosts: data_node
  roles:
    - role: elastic.elasticsearch
  vars:
    es_data_dirs:
      - "/opt/elasticsearch"
    es_config:
      cluster.name: "test-cluster"
      discovery.seed_hosts: "172.26.9.59:9300,172.26.9.6:9300,172.26.9.60:9300"
      http.port: 9200
      node.data: true
      node.master: false
      bootstrap.memory_lock: false
    es_plugins:
      - plugin: ingest-attachment
```

/etc/elasticsearch/elasticsearch.yml
```
bootstrap.memory_lock: false
cluster.initial_master_nodes: '[Undefined, Undefined, Undefined]'
cluster.name: test-cluster
```

```
ansible --version
ansible 2.7.0
  config file = /home/centos/elasticsearch/ansible.cfg
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

**Comment by Gurpartap** [comment]
`private_ip_address` is a custom hostvar that would have to be defined in the inventory… but ignore that. That's unnecessary if…

You can simply set `cluster.initial_master_nodes` just as you're setting your `discovery.seed_hosts`, except without the port numbers.

**Comment by patsevanton** [comment]
Inventory
```
[master_node]
172.26.9.70
172.26.9.71
172.26.9.72
[data_node]
172.26.9.70
172.26.9.71
172.26.9.72
```

```
- hosts: master_node
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "10g"
    es_config:
      cluster.name: "test-cluster"
      cluster.initial_master_nodes: "172.26.9.70,172.26.9.71,172.26.9.72"
      discovery.seed_hosts: "172.26.9.70:9300,172.26.9.71:9300,172.26.9.72:9300"
      http.port: 9200
      node.data: false
      node.master: true
      bootstrap.memory_lock: false
    es_plugins:
     - plugin: ingest-attachment

- hosts: data_node
  roles:
    - role: elastic.elasticsearch
  vars:
    es_data_dirs:
      - "/opt/elasticsearch"
    es_config:
      cluster.name: "test-cluster"
      discovery.seed_hosts: "172.26.9.70:9300,172.26.9.71:9300,172.26.9.72:9300"
      http.port: 9200
      node.data: true
      node.master: false
      bootstrap.memory_lock: false
    es_plugins:
      - plugin: ingest-attachment
```

```
cat elasticsearch.yml 

bootstrap.memory_lock: false
cluster.name: test-cluster
discovery.seed_hosts: 172.26.9.70:9300,172.26.9.71:9300,172.26.9.72:9300
http.port: 9200
node.data: true
node.master: false

node.name: 172.26.9.72
#################################### Paths ####################################
# Path to directory containing configuration (this file and logging.yml):
path.data: /opt/elasticsearch
path.logs: /var/log/elasticsearch
action.auto_create_index: true
```

Full ansible log
https://gist.github.com/patsevanton/899fa5aa29584d85bb1d8a991e7e9373

**Comment by Gurpartap** [comment]
Set `cluster.initial_master_nodes` for `data_node` too.

**Comment by patsevanton** [comment]
Inventory:
```
[master_node]
172.26.9.98
172.26.9.97
172.26.9.99
[data_node]
172.26.9.98
172.26.9.97
172.26.9.99
```

```
- hosts: master_node
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "10g"
    es_config:
      cluster.name: "test-cluster"
      cluster.initial_master_nodes: "172.26.9.98,172.26.9.97,172.26.9.99"
      discovery.seed_hosts: "172.26.9.98:9300,172.26.9.97:9300,172.26.9.99:9300"
      http.port: 9200
      node.data: false
      node.master: true
      bootstrap.memory_lock: false
    es_plugins:
     - plugin: ingest-attachment

- hosts: data_node
  roles:
    - role: elastic.elasticsearch
  vars:
    es_data_dirs:
      - "/opt/elasticsearch"
    es_config:
      cluster.name: "test-cluster"
      cluster.initial_master_nodes: "172.26.9.98,172.26.9.97,172.26.9.99"
      discovery.seed_hosts: "172.26.9.98:9300,172.26.9.97:9300,172.26.9.99:9300"
      http.port: 9200
      node.data: true
      node.master: false
      bootstrap.memory_lock: false
    es_plugins:
      - plugin: ingest-attachment
```

/var/log/elasticsearch/test-cluster.log:
```
[2019-11-09T06:00:26,183][WARN ][o.e.c.c.ClusterFormationFailureHelper] [172.26.9.97] master not discovered yet: have discovered [{172.26.9.97}{Yxc1Cx_wRR6BNqHeTrpQQw}{qpsVtm7wTsaTYEUnW7oYsA}{127.0.0.1}{127.0.0.1:9300}{dil}{ml.machine_memory=16656883712, xpack.installed=true, ml.max_open_jobs=20}]; discovery will continue using [172.26.9.98:9300, 172.26.9.97:9300, 172.26.9.99:9300] from hosts providers and [] from last-known cluster state; node term 0, last-accepted version 0 in term 0
[2019-11-09T06:00:36,184][WARN ][o.e.c.c.ClusterFormationFailureHelper] [172.26.9.97] master not discovered yet: have discovered [{172.26.9.97}{Yxc1Cx_wRR6BNqHeTrpQQw}{qpsVtm7wTsaTYEUnW7oYsA}{127.0.0.1}{127.0.0.1:9300}{dil}{ml.machine_memory=16656883712, xpack.installed=true, ml.max_open_jobs=20}]; discovery will continue using [172.26.9.98:9300, 172.26.9.97:9300, 172.26.9.99:9300] from hosts providers and [] from last-known cluster state; node term 0, last-accepted version 0 in term 0
[2019-11-09T06:00:46,184][WARN ][o.e.c.c.ClusterFormationFailureHelper] [172.26.9.97] master not discovered yet: have discovered [{172.26.9.97}{Yxc1Cx_wRR6BNqHeTrpQQw}{qpsVtm7wTsaTYEUnW7oYsA}{127.0.0.1}{127.0.0.1:9300}{dil}{ml.machine_memory=16656883712, xpack.installed=true, ml.max_open_jobs=20}]; discovery will continue using [172.26.9.98:9300, 172.26.9.97:9300, 172.26.9.99:9300] from hosts providers and [] from last-known cluster state; node term 0, last-accepted version 0 in term 0
```

**Comment by jmlrt** [comment]
Hi @patsevanton,
Is it expected that `master_node` hosts are the same as `data_node` hosts in your inventory?

From what I understand, when the first part of your playbook run for `master_node`, hosts `172.26.9.98`, `172.26.9.97` and `172.26.9.99` are set as master node only (no data), then when the second part of your playbook run for `data_node`, the same hosts are set as data node only (no master), so there are no more masters in your Elasticsearch cluster.

If this is not a typo in inventory and you expect to have the same nodes being master AND data nodes, you should have this instead:

- Inventory:
```
[es_node]
172.26.9.98
172.26.9.97
172.26.9.99
```

- Playbook:
```
- hosts: es_node
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "10g"
    es_data_dirs:
      - "/opt/elasticsearch"
    es_config:
      cluster.name: "test-cluster"
      cluster.initial_master_nodes: "172.26.9.98,172.26.9.97,172.26.9.99"
      discovery.seed_hosts: "172.26.9.98:9300,172.26.9.97:9300,172.26.9.99:9300"
      http.port: 9200
      node.data: true
      node.master: true
      bootstrap.memory_lock: false
    es_plugins:
     - plugin: ingest-attachment
```

**Comment by patsevanton** [comment]
_Is it expected that master_node hosts are the same as data_node hosts in your inventory?_
yes

Inventory:
```
[es_node]
172.26.9.105
172.26.9.107
172.26.9.106
```

Playbook.yml
```
- hosts: es_node
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "10g"
    es_data_dirs:
      - "/opt/elasticsearch"
    es_config:
      cluster.name: "test-cluster"
      cluster.initial_master_nodes: "172.26.9.105,172.26.9.107,172.26.9.106"
      discovery.seed_hosts: "172.26.9.105:9300,172.26.9.107:9300,172.26.9.106:9300"
      http.port: 9200
      node.data: true
      node.master: true
      bootstrap.memory_lock: false
    es_plugins:
     - plugin: ingest-attachment
```
Logs:
```
[2019-11-13T06:40:01,423][WARN ][o.e.c.c.ClusterFormationFailureHelper] [172.26.9.106] master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and this node must discover master-eligible nodes [172.26.9.105, 172.26.9.107, 172.26.9.106] to bootstrap a cluster: have discovered [{172.26.9.106}{CBhRaw7nQbSAn3mPHQHPiQ}{V7u4HhnmQ46udXE7xc-bCw}{127.0.0.1}{127.0.0.1:9300}{dilm}{ml.machine_memory=16656883712, xpack.installed=true, ml.max_open_jobs=20}]; discovery will continue using [172.26.9.105:9300, 172.26.9.107:9300, 172.26.9.106:9300] from hosts providers and [{172.26.9.106}{CBhRaw7nQbSAn3mPHQHPiQ}{V7u4HhnmQ46udXE7xc-bCw}{127.0.0.1}{127.0.0.1:9300}{dilm}{ml.machine_memory=16656883712, xpack.installed=true, ml.max_open_jobs=20}] from last-known cluster state; node term 0, last-accepted version 0 in term 0
```
