### ISSUE TITLE
How to specify global space access in users_roles?

### ISSUE THREAD

**Issue by kenorb** [elastic/ansible-elasticsearch#634]
**Elasticsearch version**: Kibana 7.1.0

**Role version**:  master

**JVM version** (`java -version`): 1.8.0_201

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 16.04

**Description of the problem including expected versus actual behaviour**:

How to specify Kibana global space access? On the [docs page](https://www.elastic.co/guide/en/elasticsearch/reference/7.1/security-api-put-role.html) it reads that `global` is _object_.

![image](https://user-images.githubusercontent.com/266306/69058337-61cd8b80-0a0b-11ea-97a4-efc0761e8215.png)

**Playbook**:

```
users_roles:
  native:
    filebeat_access:
      cluster:
        - monitor
      indices:
        - names: 'filebeat-*'
          privileges:
            - read
      global: read
```

**Provide logs from Ansible**:

Error:

>     "content": "{\"error\":{\"root_cause\":[{\"type\":\"x_content_parse_exception\",\"reason\":\"[1:98] failed to parse privilege. expected [START_OBJECT] but found [VALUE_STRING] instead\"}],\"type\":\"x_content_parse_exception\",\"reason\":\"[1:98] failed to parse privilege. expected [START_OBJECT] but found [VALUE_STRING] instead\"},\"status\":400}",

**Comment by jmlrt** [comment]
Hi @kenorb,
This question is not related to the Ansible role itself.
Can you submit it to https://discuss.elastic.co/ instead?

**Comment by kenorb** [comment]
> This question is not related to the Ansible role itself.

How it's not? I'm trying to solve this problem using this role.

**Comment by mig5** [comment]
@kenorb's question was quite valid, it was not immediately clear how to grant read only space access via the Ansible vars.

To anyone who comes across this issue, this is how I was able to add read-only access to all Kibana spaces in a native role using this Ansible role:

```
es_roles:
    native:
           somerole:
           [... access to indices etc...]
              applications:
              -   application: kibana-.kibana
                  privileges:
                  - read
                  resources: '*'
```
