### ISSUE TITLE
Setting es_user & es_group causes Elasticsearch not to start.

### ISSUE THREAD

**Issue by abickerton-upc** [elastic/ansible-elasticsearch#687]
**Elasticsearch version** 7.6.2
**Role version**:  7.6.2
**JVM version** (`java -version`): OpenJDK Runtime Environment (build 1.8.0_242-b08
**OS version** (`uname -a` if on a Unix-like system): CentOS 7

**Description of the problem including expected versus actual behaviour**:

The Elasticsearch service does not start.

**Playbook**:
```
---
- hosts: es7
  roles:
    - elastic.elasticsearch
  vars:
    es_data_dirs:
      - "/home/appuser/apps/elasticsearch/data"
    es_log_dir: "/home/appuser/apps/elasticsearch/logs"
    es_conf_dir: "/home/appuser/apps/elasticsearch/conf"
    es_pid_dir: "/home/appuser/apps/elasticsearch/pid"
    es_user: appuser
    es_group: appuser
    es_enable_xpack: true 
    es_version: 7.6.2
    es_config:
      node.name: "node1"
      transport.port: 9300
      node.master: true
      network.bind_host: "0.0.0.0"
      network.publish_host: "{{inventory_hostname}}"
      cluster.name: "cluster1"
      discovery.zen.ping.unicast.hosts: "{% for host in groups['es7'] %}{{host}}:9300,{% endfor %}localhost:9300"
      discovery.zen.minimum_master_nodes: 2
      http.port: 9200
      transport.tcp.port: 9300
      node.data: true
      bootstrap.memory_lock: false
    es_heap_size: 2g
    es_plugins:
      - plugin: ingest-attachment
```

**Provide logs from Ansible**:
[ansible.log](https://github.com/elastic/ansible-elasticsearch/files/4509595/ansible.log)
[systemd.log](https://github.com/elastic/ansible-elasticsearch/files/4509597/systemd.log)
