### ISSUE TITLE
udpate-rc.d fails on Ubuntu with multiple nodes on the same machine

### ISSUE THREAD

**Issue by jgoodall** [elastic/ansible-elasticsearch#70]
`/usr/sbin/update-rc.d` fails on Ubuntu (15.04):

```
fatal: [hostname]: FAILED! => {"changed": false, "failed": true, "msg": "Error when trying to enable node2_elasticsearch: rc=1 Synchronizing state for node2_elasticsearch.service with sysvinit using update-rc.d...\nExecuting /usr/sbin/update-rc.d node2_elasticsearch defaults\ninsserv: script node2_elasticsearch: service elasticsearch already provided!\ninsserv: exiting now!\nupdate-rc.d: error: insserv rejected the script header\n"}
```

`node2` is the `es_instance_name`. 

I believe the issue is related to the following line in the debian init script:

```
# Provides:          elasticsearch
```

Should that be something like this?

```
# Provides:          {{es_instance_name}}_{{default_file | basename}}
```

My playbook looks like this:

```
- hosts: elasticsearch
  vars:
    es_major_version: "2.x"
    es_version: "2.2.0"
    es_heap_size: "31g"
    es_max_open_files: 262140
    es_data_dir: "/elasticsearch/data"
    es_log_dir: "/elasticsearch/log"
  roles:
    - { role: elasticsearch, es_instance_name: "node1", es_config: { node.name: "node1", http.port: 9200, transport.tcp.port: 9300, cluster.name: "cluster", bootstrap.mlockall: true, discovery.zen.ping.multicast.enabled: false } }
    - { role: elasticsearch, es_instance_name: "node2", es_config: { node.name: "node2", http.port: 9201, transport.tcp.port: 9301, discovery.zen.ping.unicast.hosts: "localhost:9300", cluster.name: "cluster", bootstrap.mlockall: true, discovery.zen.ping.multicast.enabled: false } }
    - { role: elasticsearch, es_instance_name: "node3", es_config: { node.name: "node3", http.port: 9202, transport.tcp.port: 9302, discovery.zen.ping.unicast.hosts: "localhost:9300", cluster.name: "cluster", bootstrap.mlockall: true, discovery.zen.ping.multicast.enabled: false } }
```

(I assume this is also an issue on redhat, but dont have a system to test.)
