### ISSUE TITLE
Skip Java package install if java already installed

### ISSUE THREAD

**Issue by geoffroya** [elastic/ansible-elasticsearch#94]
Hello

Could it be possible to check whether Java is already present before to install it through package manager?

In my case, Oracle JDK is installed through an ansible role that download the tgz directly from Oracle.
I would like to avoid openjdk installation if not required.

For example, changing java.yml to:

```YAML
---
- name: Check Java
  shell: command -v java
    register: check_java
    ignore_errors: True
    changed_when: False

- name: RedHat - Ensure Java is installed
  yum: name={{ java }} state=latest
  when: ansible_os_family == 'RedHat' and check_java.rc > 0
  
- name: Debian - Ensure Java is installed
  apt: name={{ java }} state=present update_cache=yes force=yes
  when: ansible_os_family == 'Debian' and check_java.rc > 0
```

Best regards.

Geoff.
